package aws

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/cyberproaustin/terralift/internal/core"
	"github.com/cyberproaustin/terralift/internal/model"
	"github.com/cyberproaustin/terralift/internal/naming"
	"github.com/cyberproaustin/terralift/internal/provider"
	"github.com/cyberproaustin/terralift/internal/tf"
	"github.com/cyberproaustin/terralift/internal/util"
)

// export produces born-correct Terraform per container (region / "global") using
// native import blocks + `terraform plan -generate-config-out` — the same path
// as the GCP provider, no external export tool. Each container becomes its own
// stack with its own provider region.
func export(ctx context.Context, run *core.Run, inv *model.Inventory) (*provider.ExportResult, error) {
	byContainer := map[string][]*model.Resource{}
	for _, r := range inv.Resources {
		byContainer[r.Container] = append(byContainer[r.Container], r)
	}
	containers := make([]string, 0, len(byContainer))
	for c := range byContainer {
		containers = append(containers, c)
	}
	sort.Strings(containers)

	mode := "import"
	if run.Config.HCLOnly {
		mode = "hcl-only"
	}

	var results []provider.ContainerExport
	for _, c := range containers {
		ce, err := exportContainer(ctx, run, c, byContainer[c])
		if err != nil {
			run.Log.Warn("Export", "container %q: %v (skipping)", c, err)
			continue
		}
		results = append(results, *ce)
	}
	if len(results) == 0 {
		return nil, fmt.Errorf("export produced no containers")
	}
	return &provider.ExportResult{Mode: mode, Containers: results}, nil
}

func exportContainer(ctx context.Context, run *core.Run, container string, resources []*model.Resource) (*provider.ContainerExport, error) {
	dir := filepath.Join(run.Paths.Export, naming.Sanitize(container))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}

	// Deterministic order by ARN so born-correct suffixes are stable.
	sort.Slice(resources, func(i, j int) bool { return resources[i].ID < resources[j].ID })

	var items []*model.Resource
	var addrs []naming.Address
	var excluded, gap []string
	for _, r := range resources {
		if reason := excludedReason(r); reason != "" {
			excluded = append(excluded, r.ID)
			continue
		}
		if r.TFType == "" {
			gap = append(gap, r.ID)
			continue
		}
		items = append(items, r)
		addrs = append(addrs, naming.Address{Type: r.TFType, Base: naming.Sanitize(r.Name)})
	}
	if len(items) == 0 {
		run.Log.Info("Export", "%s: nothing to export (%d excluded, %d gap)", container, len(excluded), len(gap))
		return &provider.ContainerExport{Container: container, Dir: dir, ExcludedIDs: excluded, GapIDs: gap}, nil
	}
	names := naming.Dedupe(addrs)

	// --- born-correct import blocks + address map (for reference rewire) ---
	// Key by BARE id (the ARN's last segment), NOT the full ARN: AWS resources
	// cross-reference each other by bare id (vpc_id = "vpc-…"), so bare-id keys
	// rewire those. Keying by ARN would instead match the resource's own ARN
	// inside its inline policy — a self-reference cycle.
	addrByID := make(map[string]string, len(items))
	itemAddr := make([]string, len(items))
	var b strings.Builder
	b.WriteString("# Generated by TerraLift — born-correct import blocks.\n\n")
	for i, r := range items {
		addr := r.TFType + "." + names[i]
		itemAddr[i] = addr
		// Only rewire references to EC2 AUTO-GENERATED ids (vpc-…, sg-…, subnet-…):
		// they change on a rebuild, so a dependency reference is required. Gating on
		// the ec2 service (not just the id shape) is essential — the id regex alone
		// also matches human names with a hex-ish suffix (e.g. a bucket "db-deadbeef"
		// or "logs-20230101"), and keying those would rewrite the resource's own
		// `name = "…"` into a self-reference. Name-shaped ids stay literal (stable
		// across rebuild anyway).
		if bare := arnName(r.ID); strings.HasPrefix(r.NativeType, "ec2:") && awsGeneratedID.MatchString(bare) {
			addrByID[bare] = addr
		}
		fmt.Fprintf(&b, "import {\n  to = %s\n  id = %q\n}\n\n", addr, deriveImportID(r))
	}
	if err := os.WriteFile(filepath.Join(dir, "import.tf"), []byte(b.String()), 0o644); err != nil {
		return nil, err
	}
	writeProvidersTF(dir, regionForContainer(container))

	run.Log.Info("Export", "%s: %d import blocks (%d excluded, %d gap)", container, len(items), len(excluded), len(gap))

	// --- terraform init + generate-config-out (draft HCL; experimental) ---
	r := tf.New(dir)
	if out, err := r.Init(ctx); err != nil {
		run.Log.Warn("Export", "%s: terraform init failed: %v", container, err)
		run.Log.Verbose("Export", "%s", tail(out, 20))
	} else {
		gen := filepath.Join(dir, "generated.tf")
		out, genErr := r.GenerateConfig(ctx, gen)
		if _, statErr := os.Stat(gen); statErr == nil {
			pruned := pruneGeneratedHCL(gen)
			scrubbed := redactGeneratedHCL(gen)
			run.Log.Info("Export", "%s: generated draft HCL (%d pruned, %d scrubbed)", container, pruned, scrubbed)
		} else {
			run.Log.Warn("Export", "%s: generate-config-out produced no HCL: %v", container, genErr)
			run.Log.Verbose("Export", "%s", tail(out, 20))
		}
	}

	// Reconcile: generate-config-out can silently skip resources it can't read or
	// that are AWS-managed (no config emitted), leaving an orphan import block that
	// fails `terraform plan` with "Configuration for import target does not exist".
	// Keep only import blocks whose resource config was actually generated; the
	// rest become coverage gaps.
	generated := scanResourceAddrs(dir)
	mapped := make([]string, 0, len(items))
	var keptImports strings.Builder
	keptImports.WriteString("# Generated by TerraLift — born-correct import blocks.\n\n")
	for i, r := range items {
		if len(generated) > 0 && !generated[itemAddr[i]] {
			gap = append(gap, r.ID) // import target with no generated config
			delete(addrByID, arnName(r.ID))
			continue
		}
		mapped = append(mapped, r.ID)
		fmt.Fprintf(&keptImports, "import {\n  to = %s\n  id = %q\n}\n\n", itemAddr[i], deriveImportID(r))
	}
	if len(generated) > 0 {
		_ = os.WriteFile(filepath.Join(dir, "import.tf"), []byte(keptImports.String()), 0o644)
	}
	if len(mapped) < len(items) {
		run.Log.Info("Export", "%s: dropped %d import block(s) with no generated config", container, len(items)-len(mapped))
	}

	return &provider.ContainerExport{
		Container: container, Dir: dir,
		MappedIDs: mapped, ExcludedIDs: excluded, GapIDs: gap,
		AddressByID: addrByID, ConfigFiles: []string{"generated.tf"}, Renames: len(mapped),
	}, nil
}

// awsGeneratedID matches AWS auto-generated resource ids (a service prefix, a
// dash, then 8-17 hex chars) — vpc-…, sg-…, subnet-…, rtb-…, igw-… — but not
// human-chosen names (buckets, roles, topics), which contain non-hex text.
var awsGeneratedID = regexp.MustCompile(`^[a-z][a-z0-9]*-[0-9a-f]{8,17}$`)

var resourceLabelRe = regexp.MustCompile(`(?m)^resource\s+"([^"]+)"\s+"([^"]+)"`)

// scanResourceAddrs returns the "type.name" addresses that -generate-config-out
// actually wrote to generated.tf (empty if it produced nothing).
func scanResourceAddrs(dir string) map[string]bool {
	out := map[string]bool{}
	data, err := os.ReadFile(filepath.Join(dir, "generated.tf"))
	if err != nil {
		return out
	}
	for _, m := range resourceLabelRe.FindAllStringSubmatch(string(data), -1) {
		out[m[1]+"."+m[2]] = true
	}
	return out
}

// regionForContainer maps a layout container to a provider region. Global-service
// resources are managed from us-east-1 (where IAM/CloudFront/Route53 live).
func regionForContainer(container string) string {
	if container == "global" {
		return "us-east-1"
	}
	return container
}

func writeProvidersTF(dir, region string) {
	prov := fmt.Sprintf(`terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = %q
}
`, util.EscapeHCLTemplate(region))
	_ = os.WriteFile(filepath.Join(dir, "providers.tf"), []byte(prov), 0o644)
}

// excludedReason marks resources that are intentionally NOT onboarding targets:
// AWS-managed identities and (data-plane) secret material. Separated from genuine
// unsupported-type gaps so the coverage metric stays honest.
func excludedReason(r *model.Resource) string {
	if isDefault(r) {
		return "AWS-managed default networking (VPC/SG/NACL/route-table/subnet)"
	}
	if awsManagedDefault(r.NativeType, arnName(r.ID)) {
		return "AWS-managed default/singleton resource"
	}
	if r.NativeType == "ec2:security-group-rule" {
		return "SG rule (managed inline in aws_security_group)"
	}
	arn := strings.ToLower(r.ID)
	switch {
	case strings.Contains(arn, ":role/aws-service-role/"),
		strings.Contains(arn, ":role/aws-reserved/"):
		return "service-linked role (AWS-managed)"
	case strings.HasPrefix(arn, "arn:aws:iam::aws:"):
		return "AWS-managed IAM policy"
	}
	return ""
}

// --- generated-HCL curation (mirrors the GCP export's prune/scrub) ---

// sensitiveAttr blanks data-plane VALUE attributes that -generate-config-out can
// emit in plaintext. Matched by EXACT attribute name, never by substring — a
// broad token like `value` would wrongly blank benign config (e.g. tag values),
// so only unambiguous secret fields are listed. A heredoc opener (<<TAG) is
// handled specially: its body is consumed too (see redactGeneratedHCL).
var sensitiveAttr = regexp.MustCompile(`(?i)^(\s*)(secret_string|password|master_password|master_user_password|private_key|kms_key_material|auth_token)(\s*)=(\s*)(".*"|<<-?\w+.*)(.*)$`)

var (
	resourceHeaderRe = regexp.MustCompile(`^resource\s+"([^"]+)"\s+"[^"]+"\s*\{`)
	ssmValueRe       = regexp.MustCompile(`^(\s*)value\s*=`)
	lambdaVarsRe     = regexp.MustCompile(`^\s*variables\s*=\s*\{`)
	kvStringRe       = regexp.MustCompile(`^(\s*)([A-Za-z0-9_]+)(\s*)=\s*".*"`)
	heredocOpenRe    = regexp.MustCompile(`<<-?(\w+)`)
)

// redactGeneratedHCL blanks data-plane secret material from the generated HCL.
// It is block-aware (unlike a pure line scrub) so it can neutralize values that
// aren't recognizable by attribute name alone:
//   - exact-name secret attributes anywhere (secret_string/password/…), INCLUDING
//     multi-line heredoc bodies,
//   - a SecureString aws_ssm_parameter's `value` (a decrypted secret),
//   - every aws_lambda_function environment variable value (env vars routinely
//     hold API keys / DB creds and can't be told apart from benign config).
//
// Returns the number of values blanked.
func redactGeneratedHCL(path string) int {
	data, err := os.ReadFile(path)
	if err != nil {
		return 0
	}
	lines := strings.Split(string(data), "\n")
	n := scrubExactSecrets(lines)
	for _, b := range blockRanges(lines) {
		switch b.typ {
		case "aws_ssm_parameter":
			if rangeContains(lines, b, `"SecureString"`) {
				n += blankValueAttr(lines, b)
			}
		case "aws_lambda_function":
			n += blankLambdaVars(lines, b)
		}
	}
	if n > 0 {
		_ = os.WriteFile(path, []byte(strings.Join(lines, "\n")), 0o644)
	}
	return n
}

type hclBlock struct {
	typ        string
	start, end int
}

// blockRanges returns the line span of every top-level `resource "T" "N"` block.
func blockRanges(lines []string) []hclBlock {
	var out []hclBlock
	inBlock := false
	depth := 0
	cur := hclBlock{}
	for i, l := range lines {
		if !inBlock {
			if m := resourceHeaderRe.FindStringSubmatch(l); m != nil {
				cur = hclBlock{typ: m[1], start: i}
				depth = strings.Count(l, "{") - strings.Count(l, "}")
				if depth <= 0 {
					cur.end = i
					out = append(out, cur)
				} else {
					inBlock = true
				}
			}
			continue
		}
		depth += strings.Count(l, "{") - strings.Count(l, "}")
		if depth <= 0 {
			cur.end = i
			out = append(out, cur)
			inBlock = false
		}
	}
	return out
}

func rangeContains(lines []string, b hclBlock, needle string) bool {
	for i := b.start; i <= b.end && i < len(lines); i++ {
		if strings.Contains(lines[i], needle) {
			return true
		}
	}
	return false
}

// scrubExactSecrets blanks exact-name secret attributes and, when the value is a
// heredoc, blanks the heredoc body through its terminator.
func scrubExactSecrets(lines []string) int {
	n := 0
	for i := 0; i < len(lines); i++ {
		m := sensitiveAttr.FindStringSubmatch(lines[i])
		if m == nil {
			continue
		}
		lines[i] = m[1] + m[2] + m[3] + "=" + m[4] + `"" # TerraLift: scrubbed sensitive value`
		n++
		if hm := heredocOpenRe.FindStringSubmatch(m[5]); hm != nil {
			tag := hm[1]
			for j := i + 1; j < len(lines); j++ {
				done := strings.TrimSpace(lines[j]) == tag
				lines[j] = "" // drop body + terminator so no secret and no dangling heredoc
				if done {
					i = j
					break
				}
			}
		}
	}
	return n
}

// blankValueAttr blanks the first `value = …` line within a block (SecureString
// SSM parameter). Value may span a heredoc; consume it too.
func blankValueAttr(lines []string, b hclBlock) int {
	for i := b.start; i <= b.end && i < len(lines); i++ {
		m := ssmValueRe.FindStringSubmatch(lines[i])
		if m == nil {
			continue
		}
		rest := lines[i][len(m[0]):]
		lines[i] = m[1] + `value = "" # TerraLift: scrubbed SecureString value`
		if hm := heredocOpenRe.FindStringSubmatch(rest); hm != nil {
			for j := i + 1; j <= b.end && j < len(lines); j++ {
				done := strings.TrimSpace(lines[j]) == hm[1]
				lines[j] = ""
				if done {
					break
				}
			}
		}
		return 1
	}
	return 0
}

// blankLambdaVars blanks every value in a lambda's `variables = { … }` map.
func blankLambdaVars(lines []string, b hclBlock) int {
	n, depth := 0, 0
	inVars := false
	for i := b.start; i <= b.end && i < len(lines); i++ {
		l := lines[i]
		if !inVars {
			if lambdaVarsRe.MatchString(l) {
				inVars = true
				depth = strings.Count(l, "{") - strings.Count(l, "}")
			}
			continue
		}
		depth += strings.Count(l, "{") - strings.Count(l, "}")
		if depth <= 0 {
			inVars = false
			continue
		}
		if m := kvStringRe.FindStringSubmatch(l); m != nil {
			lines[i] = m[1] + m[2] + m[3] + `= "" # TerraLift: scrubbed lambda env value`
			n++
		}
	}
	return n
}

// emptyAttr matches attributes -generate-config-out over-emits as `null` (always
// safe to omit — the provider applies its default). Unlike GCP, AWS is NOT pruned
// of empty lists/maps ([]/{}): its inline blocks (e.g. aws_security_group ingress)
// REQUIRE every attribute present, so dropping an empty list breaks validation.
var emptyAttr = regexp.MustCompile(`^\s*[A-Za-z0-9_]+\s*=\s*null\s*$`)

// overEmitAttr matches attributes -generate-config-out emits with a default that
// is INVALID unless sibling attributes are also set (e.g. the Outpost trio on a
// subnet — map_customer_owned_ip_on_launch requires customer_owned_ipv4_pool +
// outpost_arn). Dropping the whole group lets the provider apply real defaults.
var overEmitAttr = regexp.MustCompile(`^\s*(map_customer_owned_ip_on_launch|customer_owned_ipv4_pool|outpost_arn|availability_zone_id|ipv6_netmask_length|ipv6_ipam_pool_id|recovery_period_in_days|enable_lni_at_device_index|signature_version|name_prefix|datapoints_to_alarm|rotation_period_in_days)\s*=`)

func pruneGeneratedHCL(path string) int {
	data, err := os.ReadFile(path)
	if err != nil {
		return 0
	}
	lines := strings.Split(string(data), "\n")
	out := make([]string, 0, len(lines))
	n := 0
	for _, l := range lines {
		if emptyAttr.MatchString(l) || overEmitAttr.MatchString(l) {
			n++
			continue
		}
		out = append(out, l)
	}
	if n > 0 {
		_ = os.WriteFile(path, []byte(strings.Join(out, "\n")), 0o644)
	}
	return n
}

func tail(s string, lines int) string {
	parts := strings.Split(strings.TrimRight(s, "\n"), "\n")
	if len(parts) > lines {
		parts = parts[len(parts)-lines:]
	}
	return strings.Join(parts, "\n")
}
