package aws

import (
	"archive/zip"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/cyberproaustin/terralift/internal/core"
	"github.com/cyberproaustin/terralift/internal/hcl"
	"github.com/cyberproaustin/terralift/internal/model"
	"github.com/cyberproaustin/terralift/internal/naming"
	"github.com/cyberproaustin/terralift/internal/provider"
	"github.com/cyberproaustin/terralift/internal/tf"
	"github.com/cyberproaustin/terralift/internal/util"
)

// export produces born-correct Terraform per container (region / "global") using
// native import blocks + `terraform plan -generate-config-out` — the same path
// as the GCP provider, no external export tool. Each container becomes its own
// stack with its own provider region.
func export(ctx context.Context, run *core.Run, inv *model.Inventory) (*provider.ExportResult, error) {
	byContainer := map[string][]*model.Resource{}
	for _, r := range inv.Resources {
		byContainer[r.Container] = append(byContainer[r.Container], r)
	}
	containers := make([]string, 0, len(byContainer))
	for c := range byContainer {
		containers = append(containers, c)
	}
	sort.Strings(containers)

	mode := "import"
	if run.Config.HCLOnly {
		mode = "hcl-only"
	}

	var results []provider.ContainerExport
	for _, c := range containers {
		ce, err := exportContainer(ctx, run, c, byContainer[c])
		if err != nil {
			run.Log.Warn("Export", "container %q: %v (skipping)", c, err)
			continue
		}
		results = append(results, *ce)
	}
	if len(results) == 0 {
		return nil, fmt.Errorf("export produced no containers")
	}
	return &provider.ExportResult{Mode: mode, Containers: results}, nil
}

func exportContainer(ctx context.Context, run *core.Run, container string, resources []*model.Resource) (*provider.ContainerExport, error) {
	dir := filepath.Join(run.Paths.Export, naming.Sanitize(container))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}

	// Deterministic order by ARN so born-correct suffixes are stable.
	sort.Slice(resources, func(i, j int) bool { return resources[i].ID < resources[j].ID })

	var items []*model.Resource
	var addrs []naming.Address
	var excluded, gap []string
	for _, r := range resources {
		if reason := excludedReason(r); reason != "" {
			excluded = append(excluded, r.ID)
			continue
		}
		if r.TFType == "" {
			gap = append(gap, r.ID)
			continue
		}
		items = append(items, r)
		addrs = append(addrs, naming.Address{Type: r.TFType, Base: naming.Sanitize(r.Name)})
	}
	if len(items) == 0 {
		run.Log.Info("Export", "%s: nothing to export (%d excluded, %d gap)", container, len(excluded), len(gap))
		return &provider.ContainerExport{Container: container, Dir: dir, ExcludedIDs: excluded, GapIDs: gap}, nil
	}
	names := naming.Dedupe(addrs)

	// --- born-correct import blocks + address map (for reference rewire) ---
	// Key by BARE id (the ARN's last segment), NOT the full ARN: AWS resources
	// cross-reference each other by bare id (vpc_id = "vpc-…"), so bare-id keys
	// rewire those. Keying by ARN would instead match the resource's own ARN
	// inside its inline policy — a self-reference cycle.
	addrByID := make(map[string]string, len(items))
	itemAddr := make([]string, len(items))
	crossRef := make(map[string][]refTarget, len(items)) // for typed cross-reference rewiring
	var b strings.Builder
	b.WriteString("# Generated by TerraLift — born-correct import blocks.\n\n")
	for i, r := range items {
		addr := r.TFType + "." + names[i]
		itemAddr[i] = addr
		crossRef[r.TFType] = append(crossRef[r.TFType], refTarget{addr: addr, name: r.Name, id: arnName(r.ID), arn: r.ID})
		// Only rewire references to EC2 AUTO-GENERATED ids (vpc-…, sg-…, subnet-…):
		// they change on a rebuild, so a dependency reference is required. Gating on
		// the ec2 service (not just the id shape) is essential — the id regex alone
		// also matches human names with a hex-ish suffix (e.g. a bucket "db-deadbeef"
		// or "logs-20230101"), and keying those would rewrite the resource's own
		// `name = "…"` into a self-reference. Name-shaped ids stay literal (stable
		// across rebuild anyway).
		if bare := arnName(r.ID); strings.HasPrefix(r.NativeType, "ec2:") && awsGeneratedID.MatchString(bare) {
			addrByID[bare] = addr + ".id" // Rewire now takes the full reference expression
		}
		fmt.Fprintf(&b, "import {\n  to = %s\n  id = %q\n}\n\n", addr, deriveImportID(r))
	}
	if err := os.WriteFile(filepath.Join(dir, "import.tf"), []byte(b.String()), 0o644); err != nil {
		return nil, err
	}
	writeProvidersTF(dir, regionForContainer(container))

	run.Log.Info("Export", "%s: %d import blocks (%d excluded, %d gap)", container, len(items), len(excluded), len(gap))

	// --- terraform init + generate-config-out (draft HCL; experimental) ---
	var redactions []hcl.Redaction
	r := tf.New(dir)
	if out, err := r.Init(ctx); err != nil {
		run.Log.Warn("Export", "%s: terraform init failed: %v", container, err)
		run.Log.Verbose("Export", "%s", tail(out, 20))
	} else {
		gen := filepath.Join(dir, "generated.tf")
		out, genErr := r.GenerateConfig(ctx, gen)
		if _, statErr := os.Stat(gen); statErr == nil {
			// Redact BEFORE prune: a required secret attribute that
			// generate-config-out emits as `value = null # sensitive` (e.g. an SSM
			// SecureString, whose value can't be read) must be turned into a blanked
			// value + ignore_changes by the redactor, not stripped by the prune (which
			// would leave the required argument missing).
			redactions = redactGeneratedHCL(gen)
			pruned := pruneGeneratedHCL(gen)
			blockified := blockifyInlineRules(gen)
			redactions = append(redactions, curateAWSGenerated(gen, run.Scope.ID)...)
			authored := authorKeyPairs(ctx, gen, regionForContainer(container), items, itemAddr, crossRef)
			authored += authorTaskDefs(ctx, gen, regionForContainer(container), items, itemAddr)
			listeners := authorListeners(ctx, gen, regionForContainer(container), items, itemAddr)
			addEcsListenerDeps(gen, allListenerAddrs(gen)) // ALL listeners (authored + generate-config-out)
			authored += len(listeners)
			xref := rewireCrossRefs(gen, crossRef)
			run.Log.Info("Export", "%s: generated draft HCL (%d pruned, %d rule-blocks, %d cross-refs, %d authored, %d scrubbed/placeholder)", container, pruned, blockified, xref, authored, len(redactions))
		} else {
			run.Log.Warn("Export", "%s: generate-config-out produced no HCL: %v", container, genErr)
			run.Log.Verbose("Export", "%s", tail(out, 20))
		}
	}

	// Reconcile: an import block is only usable if generate-config-out actually
	// emitted matching config. Any address absent from generated.tf is a gap —
	// this INCLUDES the case where generation produced nothing at all (init/plan
	// failed), which must be reported honestly as all-gap, never silently as 100%
	// mapped over an unusable artifact. (An orphan import block with no config also
	// fails `terraform plan` with "Configuration for import target does not exist".)
	generated := scanResourceAddrs(dir)
	mapped := make([]string, 0, len(items))
	var keptImports strings.Builder
	keptImports.WriteString("# Generated by TerraLift — born-correct import blocks.\n\n")
	for i, r := range items {
		if !generated[itemAddr[i]] {
			gap = append(gap, r.ID) // import target with no generated config
			delete(addrByID, arnName(r.ID))
			continue
		}
		mapped = append(mapped, r.ID)
		fmt.Fprintf(&keptImports, "import {\n  to = %s\n  id = %q\n}\n\n", itemAddr[i], deriveImportID(r))
	}
	// Always rewrite import.tf to only the kept blocks (comment-only if none), so no
	// orphan import block is left behind to break `terraform plan`.
	_ = os.WriteFile(filepath.Join(dir, "import.tf"), []byte(keptImports.String()), 0o644)
	if len(mapped) < len(items) {
		run.Log.Info("Export", "%s: dropped %d import block(s) with no generated config", container, len(items)-len(mapped))
	}

	return &provider.ContainerExport{
		Container: container, Dir: dir,
		MappedIDs: mapped, ExcludedIDs: excluded, GapIDs: gap,
		AddressByID: addrByID, ConfigFiles: []string{"generated.tf"},
		Redactions: redactions,
	}, nil
}

// awsGeneratedID matches AWS auto-generated resource ids (a service prefix, a
// dash, then 8-17 hex chars) — vpc-…, sg-…, subnet-…, rtb-…, igw-… — but not
// human-chosen names (buckets, roles, topics), which contain non-hex text.
var awsGeneratedID = regexp.MustCompile(`^[a-z][a-z0-9]*-[0-9a-f]{8,17}$`)

var resourceLabelRe = regexp.MustCompile(`(?m)^resource\s+"([^"]+)"\s+"([^"]+)"`)

// scanResourceAddrs returns the "type.name" addresses that -generate-config-out
// actually wrote to generated.tf (empty if it produced nothing).
func scanResourceAddrs(dir string) map[string]bool {
	out := map[string]bool{}
	data, err := os.ReadFile(filepath.Join(dir, "generated.tf"))
	if err != nil {
		return out
	}
	for _, m := range resourceLabelRe.FindAllStringSubmatch(string(data), -1) {
		out[m[1]+"."+m[2]] = true
	}
	return out
}

// regionForContainer maps a layout container to a provider region. Global-service
// resources are managed from us-east-1 (where IAM/CloudFront/Route53 live).
func regionForContainer(container string) string {
	if container == "global" {
		return "us-east-1"
	}
	return container
}

func writeProvidersTF(dir, region string) {
	prov := fmt.Sprintf(`terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = %q
}
`, util.EscapeHCLTemplate(region))
	_ = os.WriteFile(filepath.Join(dir, "providers.tf"), []byte(prov), 0o644)
}

// excludedReason marks resources that are intentionally NOT onboarding targets:
// AWS-managed identities and (data-plane) secret material. Separated from genuine
// unsupported-type gaps so the coverage metric stays honest.
func excludedReason(r *model.Resource) string {
	if isDefault(r) {
		return "AWS-managed default networking (VPC/SG/NACL/route-table/subnet)"
	}
	if awsManagedDefault(r.NativeType, arnName(r.ID)) {
		return "AWS-managed default/singleton resource"
	}
	if r.NativeType == "ec2:security-group-rule" {
		return "SG rule (managed inline in aws_security_group)"
	}
	if r.NativeType == "ec2:network-interface" && isManagedENI(r) {
		return "service/instance-managed network interface (not standalone)"
	}
	if v, _ := r.Properties["tl_caller"].(bool); v {
		return "the onboarding principal itself (caller identity)"
	}
	arn := strings.ToLower(r.ID)
	switch {
	case strings.Contains(arn, ":role/aws-service-role/"),
		strings.Contains(arn, ":role/aws-reserved/"):
		return "service-linked role (AWS-managed)"
	// AWS-managed policy ARN is arn:<partition>:iam::aws:policy/… — match the
	// account-less ":iam::aws:" segment so GovCloud (aws-us-gov) and China (aws-cn)
	// partitions are excluded too, not just the commercial one.
	case strings.HasPrefix(arn, "arn:") && strings.Contains(arn, ":iam::aws:"):
		return "AWS-managed IAM policy"
	}
	return ""
}

// --- generated-HCL curation (mirrors the GCP export's prune/scrub) ---

// awsSecretAttrs are exact attribute names that are UNAMBIGUOUS single secret
// values (not config) — the shared redactor removes them (heredoc-aware). App
// config (Lambda env, ECS container env) is intentionally NOT redacted; it ships
// and is flagged in the secrets-review report instead.
var awsSecretAttrs = []string{
	"secret_string", "secret_binary", "password", "master_password",
	"master_user_password", "private_key", "key_material_base64", "auth_token",
}

// awsRedactRules redact declared-secret values. A SecureString SSM parameter's
// value is a declared secret (unlike an env-var map), so it's blanked +
// ignore_changes-protected rather than shipped.
var awsRedactRules = []hcl.Rule{
	{Type: "aws_ssm_parameter", Attr: "value", Kind: hcl.Scalar, OnlyIfContains: `"SecureString"`},
	// An API Gateway API key's `value` IS the literal key secret and is
	// Sensitive+Optional/Computed — `-generate-config-out` does not redact Sensitive
	// attributes, so it would ship in cleartext. Scoped to the resource type so bare
	// `value` elsewhere (e.g. plain SSM String params) is untouched.
	{Type: "aws_api_gateway_api_key", Attr: "value", Kind: hcl.Scalar},
}

// redactGeneratedHCL removes data-plane secret material from the generated HCL via
// the shared, structure-aware redactor (heredoc- and block-aware) and returns the
// list of scrubbed secrets for the operator-facing redactions report.
func redactGeneratedHCL(path string) []hcl.Redaction {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	out, events := hcl.Redact(string(data), awsSecretAttrs, awsRedactRules)
	if len(events) > 0 {
		_ = os.WriteFile(path, []byte(out), 0o644)
	}
	return events
}

// emptyAttr matches attributes -generate-config-out over-emits as `null` (always
// safe to omit — the provider applies its default). Unlike GCP, AWS is NOT pruned
// of empty lists/maps ([]/{}): its inline blocks (e.g. aws_security_group ingress)
// REQUIRE every attribute present, so dropping an empty list breaks validation.
// emptyAttr matches an attribute -generate-config-out over-emits as an empty
// value: null, [], or {} — optionally trailed by a comment it adds (e.g.
// `value = null # sensitive`). These are noise at best and, for mutually-exclusive
// pairs (ipv4_prefixes=[] beside ipv4_prefix_count=0) or empty required lists
// (security_group_names=[], vpc_endpoint_ids=[]), actively break the plan.
var emptyAttr = regexp.MustCompile(`^\s*[A-Za-z0-9_]+\s*=\s*(null|\[\]|\{\})\s*(#.*)?$`)

// generatedComment matches the boilerplate generate-config-out sprinkles through
// its output ("# __generated__ by Terraform", "# Please review these resources…").
// It is pure noise in the onboarding repo, so strip it.
var generatedComment = regexp.MustCompile(`^\s*#\s*(__generated__ by Terraform|Please review these resources)`)

// emptyCIDR matches an empty cidr_block / ipv6_cidr_block generate-config-out emits
// as the unused sibling of a rule (an IPv6 NACL rule still gets cidr_block = "",
// and vice versa) — an empty string is never a valid CIDR, so drop it.
var emptyCIDR = regexp.MustCompile(`^\s*(cidr_block|ipv6_cidr_block)\s*=\s*""\s*(#.*)?$`)

// overEmitAttr matches attributes -generate-config-out emits with a default that
// is INVALID unless sibling attributes are also set (e.g. the Outpost trio on a
// subnet — map_customer_owned_ip_on_launch requires customer_owned_ipv4_pool +
// outpost_arn). Dropping the whole group lets the provider apply real defaults.
var overEmitAttr = regexp.MustCompile(`^\s*(map_customer_owned_ip_on_launch|customer_owned_ipv4_pool|outpost_arn|availability_zone_id|ipv6_netmask_length|ipv6_ipam_pool_id|recovery_period_in_days|enable_lni_at_device_index|signature_version|name_prefix|datapoints_to_alarm|rotation_period_in_days)\s*=`)

func pruneGeneratedHCL(path string) int {
	data, err := os.ReadFile(path)
	if err != nil {
		return 0
	}
	lines := strings.Split(string(data), "\n")
	out := make([]string, 0, len(lines))
	n := 0
	for _, l := range lines {
		if emptyAttr.MatchString(l) || overEmitAttr.MatchString(l) || emptyCIDR.MatchString(l) || generatedComment.MatchString(l) {
			n++
			continue
		}
		out = append(out, l)
	}
	if n > 0 {
		_ = os.WriteFile(path, []byte(strings.Join(out, "\n")), 0o644)
	}
	return n
}

var inlineRuleOpen = regexp.MustCompile(`^(\s*)(route|ingress|egress)\s*=\s*\[\{\s*$`)

// blockifyInlineRules rewrites generate-config-out's attribute-list syntax for the
// block-typed attributes route/ingress/egress (`route = [{ … }]`) into repeated
// block syntax (`route { … }`). The attribute-list form fails `terraform plan` with
// "Incorrect attribute value type": its object literal omits optional keys, so it
// doesn't match the schema's full object type, whereas a block accepts omitted
// optionals. Scoped to these attributes only (an IAM-policy `Statement = [{…}]`
// must NOT be touched), tracking each list's own `}]` closer and `}, {` separator.
func blockifyInlineRules(path string) int {
	data, err := os.ReadFile(path)
	if err != nil {
		return 0
	}
	lines := strings.Split(string(data), "\n")
	out := make([]string, 0, len(lines))
	n := 0
	for i := 0; i < len(lines); i++ {
		m := inlineRuleOpen.FindStringSubmatch(lines[i])
		if m == nil {
			out = append(out, lines[i])
			continue
		}
		indent, attr := m[1], m[2]
		out = append(out, indent+attr+" {")
		n++
		for i++; i < len(lines); i++ {
			switch strings.TrimSpace(lines[i]) {
			case "}]": // end of the list
				out = append(out, indent+"}")
			case "}, {", "},{": // next object in the same list -> a new block
				out = append(out, indent+"}")
				out = append(out, indent+attr+" {")
				continue
			default:
				out = append(out, lines[i])
				continue
			}
			break // only the "}]" case falls through to here
		}
	}
	if n > 0 {
		_ = os.WriteFile(path, []byte(strings.Join(out, "\n")), 0o644)
	}
	return n
}

var (
	resHeaderRe  = regexp.MustCompile(`^resource\s+"([^"]+)"\s+"([^"]+)"\s*\{`)
	ssmValueRe   = regexp.MustCompile(`^\s*(value|insecure_value|value_wo)\s*=`)
	codeSourceRe = regexp.MustCompile(`^\s*(filename|s3_bucket|image_uri)\s*=`)
	// emptyBlockReq: optional nested blocks generate-config-out over-emits with only
	// computed/empty content, missing their required child argument. Dropping the
	// whole (optional) block is safe and clears the "Missing required argument" error.
	emptyBlockReq = map[string]string{
		"target_failover":     "on_deregistration",
		"target_health_state": "enable_unhealthy_connection_termination",
	}
)

// curateAWSGenerated applies the structural fixes generate-config-out's output
// needs that prune/redact/blockify don't: drop over-emitted empty/conflicting
// blocks, and per resource type — inject placeholders for values AWS won't return
// (SSM value, Lambda code), drop conflicting attributes (aws_elb availability_zones
// vs subnets), and add the create-time arguments a greenfield re-apply needs
// (VPC-peering auto_accept, KMS bypass_policy_lockout). Placeholders are recorded
// for reports/redactions.md. account is the caller's account id (for same-account
// peering detection).
func curateAWSGenerated(path, account string) []hcl.Redaction {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	lines := dropEmptyBlocks(strings.Split(string(data), "\n"))
	lines = dropOverEmitLists(lines)
	lines = dropOverEmitStickiness(lines)
	lines, events := processBlocks(lines, account)
	_ = os.WriteFile(path, []byte(strings.Join(lines, "\n")), 0o644)
	for _, e := range events {
		if e.Resource == "aws_lambda_function" { // a filename placeholder needs its zip shipped
			writeLambdaPlaceholderZip(filepath.Dir(path))
			break
		}
	}
	return events
}

// writeLambdaPlaceholderZip ships a minimal valid deployment package next to the
// config so a `filename = "lambda_placeholder.zip"` placeholder applies out of the
// box (the operator replaces it with their real code).
func writeLambdaPlaceholderZip(dir string) {
	p := filepath.Join(dir, "lambda_placeholder.zip")
	if _, err := os.Stat(p); err == nil {
		return
	}
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	if w, err := zw.Create("index.py"); err == nil {
		_, _ = w.Write([]byte("def handler(event, context):\n    # TerraLift placeholder — replace with your real code.\n    return {\"statusCode\": 200, \"body\": \"placeholder\"}\n"))
	}
	_ = zw.Close()
	_ = os.WriteFile(p, buf.Bytes(), 0o644)
}

var (
	subnetsAttrRe = regexp.MustCompile(`^\s*subnets\s*=`)
	azAttrRe      = regexp.MustCompile(`^\s*availability_zones\s*=`)
	policyAttrRe  = regexp.MustCompile(`^\s*policy\s*=`)
	autoAcceptRe  = regexp.MustCompile(`^\s*auto_accept\s*=`)
	bypassRe      = regexp.MustCompile(`bypass_policy_lockout`)
	peerRegionRe  = regexp.MustCompile(`^\s*peer_region\s*=`)
	iamRoleRe     = regexp.MustCompile(`^\s*iam_role\s*=`)
	emptyValueRe  = regexp.MustCompile(`^\s*value\s*=\s*""`)
	gatewayTypeRe    = regexp.MustCompile(`vpc_endpoint_type\s*=\s*"Gateway"`)
	targetGroupArnRe = regexp.MustCompile(`^\s*target_group_arn\s*=`)
)

// processBlocks walks each resource block and applies type-specific create-readiness
// curation (see curateAWSGenerated).
func processBlocks(lines []string, account string) ([]string, []hcl.Redaction) {
	var out []string
	var events []hcl.Redaction
	for i := 0; i < len(lines); i++ {
		m := resHeaderRe.FindStringSubmatch(lines[i])
		if m == nil {
			out = append(out, lines[i])
			continue
		}
		depth, end := hcl.BraceDelta(lines[i]), i
		for j := i + 1; j < len(lines); j++ {
			depth += hcl.BraceDelta(lines[j])
			if depth <= 0 {
				end = j
				break
			}
		}
		block, evs := curateBlock(m[1], lines[i:end+1], account)
		events = append(events, evs...)
		out = append(out, block...)
		i = end
	}
	return out, events
}

func curateBlock(typ string, block []string, account string) ([]string, []hcl.Redaction) {
	if len(block) < 2 {
		return block, nil
	}
	body := append([]string{}, block[1:len(block)-1]...)
	closing := block[len(block)-1]
	var events []hcl.Redaction
	var inject []string
	switch typ {
	case "aws_ssm_parameter":
		switch {
		case !anyMatches(body, ssmValueRe):
			// A CREATE-valid placeholder (non-empty; "" is rejected) + ignore_changes:
			// import ignores it (state has the real value), a from-scratch apply sets
			// the stub. Operator replaces it (documented in redactions.md).
			inject = []string{
				`  value = "REPLACE_ME" # TerraLift: value not retrievable (sensitive) — replace with the real value`,
				`  lifecycle { ignore_changes = [value] }`,
			}
			events = append(events, hcl.Redaction{Resource: typ, Attr: "value", Action: "placeholder"})
		case anyMatches(body, emptyValueRe):
			// The redactor blanked a SecureString value to "" — create-invalid (min
			// length 1). Make it the create-valid placeholder instead.
			for i, l := range body {
				if emptyValueRe.MatchString(l) {
					body[i] = strings.Replace(l, `""`, `"REPLACE_ME"`, 1)
				}
			}
		}
	case "aws_lambda_function":
		if !anyMatches(body, codeSourceRe) {
			// Reference a self-contained placeholder .zip shipped in the stack (see
			// writeLambdaPlaceholderZip) so the repo applies with NO manual edits; the
			// operator swaps in their real deployment package. ignore_changes keeps an
			// import plan clean (the live code is untouched).
			inject = []string{
				`  filename = "lambda_placeholder.zip" # TerraLift: code not retrievable — replace with your real deployment package`,
				`  lifecycle { ignore_changes = [filename, source_code_hash, s3_bucket, s3_key, image_uri] }`,
			}
			events = append(events, hcl.Redaction{Resource: typ, Attr: "filename", Action: "placeholder"})
		}
	case "aws_elb":
		if anyMatches(body, subnetsAttrRe) { // subnets + availability_zones conflict — keep subnets
			body = dropLines(body, azAttrRe)
		}
	case "aws_vpc_peering_connection":
		if !anyMatches(body, autoAcceptRe) && sameAccountPeer(body, account) {
			// auto_accept conflicts with peer_region; a same-account, same-region
			// peering doesn't need peer_region, so drop it. auto_accept is a create-time
			// flag AWS never returns on read — ignore_changes keeps the import plan clean
			// (the flag still drives a from-scratch rebuild).
			body = dropLines(body, peerRegionRe)
			inject = []string{
				`  auto_accept = true # TerraLift: same-account peering auto-accepts on rebuild`,
				`  lifecycle { ignore_changes = [auto_accept] }`,
			}
		}
	case "aws_kms_key":
		if anyMatches(body, policyAttrRe) && !anyMatches(body, bypassRe) {
			// bypass_policy_lockout_safety_check is a create-time-only flag AWS does not
			// return on read; without ignore_changes it shows as a spurious import diff on
			// every key. It still protects a from-scratch rebuild of the live policy.
			inject = []string{
				`  bypass_policy_lockout_safety_check = true # TerraLift: policy is the imported live policy`,
				`  lifecycle { ignore_changes = [bypass_policy_lockout_safety_check] }`,
			}
		}
	case "aws_secretsmanager_secret":
		// recovery_window_in_days and force_overwrite_replica_secret are delete-/replica-
		// time-only params AWS never returns on read, so an import plan shows the provider
		// defaults as spurious additions. ignore_changes keeps adoption plan-clean.
		inject = []string{`  lifecycle { ignore_changes = [recovery_window_in_days, force_overwrite_replica_secret] }`}
	case "aws_ecs_service":
		// An awsvpc/Fargate service uses the ECS service-linked role automatically and
		// REJECTS an explicit iam_role. generate-config-out over-emits it; drop it.
		// wait_for_steady_state is a Terraform-only apply-wait flag AWS doesn't store.
		body = dropLines(body, iamRoleRe)
		inject = []string{`  lifecycle { ignore_changes = [wait_for_steady_state] }`}
	case "aws_vpc_endpoint":
		// A Gateway endpoint (S3/DynamoDB) rejects the dns_options block that only
		// applies to Interface endpoints; generate-config-out over-emits it.
		if anyMatches(body, gatewayTypeRe) {
			body = dropNestedBlock(body, "dns_options")
		}
	case "aws_lb_listener":
		// generate-config-out over-emits BOTH the shorthand `target_group_arn` and a
		// `forward {}` block, which conflict unless their ARNs match (and after
		// reference-rewiring they won't textually). Keep the shorthand, drop forward.
		if anyMatches(body, targetGroupArnRe) {
			body = dropNestedBlock(body, "forward")
		}
	}
	result := append([]string{block[0]}, body...)
	result = append(result, inject...)
	return append(result, closing), events
}

// dropOverEmitStickiness removes a `stickiness { … }` block that generate-config-out
// over-emits with duration = 0, which fails validation (duration must be 1..604800);
// a disabled stickiness doesn't need the block at all.
func dropOverEmitStickiness(lines []string) []string {
	out := make([]string, 0, len(lines))
	for i := 0; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) == "stickiness {" {
			j, depth := i+1, 1
			var body []string
			for ; j < len(lines) && depth > 0; j++ {
				depth += strings.Count(lines[j], "{") - strings.Count(lines[j], "}")
				if depth > 0 {
					body = append(body, lines[j])
				}
			}
			over := false
			for _, bl := range body {
				if strings.Contains(bl, "duration") && strings.Contains(bl, "= 0") {
					over = true
				}
			}
			if over {
				i = j - 1 // skip the whole block including its closing brace
				continue
			}
		}
		out = append(out, lines[i])
	}
	return out
}

// allListenerAddrs returns every declared aws_lb_listener address in the file.
func allListenerAddrs(path string) []string {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	var out []string
	for _, m := range resourceLabelRe.FindAllStringSubmatch(string(data), -1) {
		if m[1] == "aws_lb_listener" {
			out = append(out, "aws_lb_listener."+m[2])
		}
	}
	return out
}

// dropNestedBlock removes a `<name> { … }` nested block (brace-balanced, so it
// handles blocks that themselves contain nested blocks) from a block body.
func dropNestedBlock(body []string, name string) []string {
	out := make([]string, 0, len(body))
	for i := 0; i < len(body); i++ {
		if strings.TrimSpace(body[i]) == name+" {" {
			depth, j := 1, i+1
			for ; j < len(body) && depth > 0; j++ {
				depth += strings.Count(body[j], "{") - strings.Count(body[j], "}")
			}
			i = j - 1 // outer loop's i++ lands past the closing brace
			continue
		}
		out = append(out, body[i])
	}
	return out
}

func dropLines(lines []string, re *regexp.Regexp) []string {
	out := lines[:0]
	for _, l := range lines {
		if !re.MatchString(l) {
			out = append(out, l)
		}
	}
	return out
}

// sameAccountPeer reports whether a peering block is same-account (its peer_owner_id
// matches the caller, or is absent — which defaults to the caller's account).
func sameAccountPeer(body []string, account string) bool {
	for _, l := range body {
		if strings.Contains(l, "peer_owner_id") {
			return account != "" && strings.Contains(l, `"`+account+`"`)
		}
	}
	return true // no peer_owner_id -> same account by default
}

func dropEmptyBlocks(lines []string) []string {
	out := make([]string, 0, len(lines))
	for i := 0; i < len(lines); i++ {
		t := strings.TrimSpace(lines[i])
		if name := strings.TrimSuffix(t, " {"); strings.HasSuffix(t, "{") {
			if req, ok := emptyBlockReq[name]; ok {
				j := i + 1
				has := false
				for ; j < len(lines) && strings.TrimSpace(lines[j]) != "}"; j++ {
					if strings.Contains(lines[j], req) {
						has = true
					}
				}
				if !has {
					i = j // skip the whole block including its closing "}"
					continue
				}
			}
		}
		out = append(out, lines[i])
	}
	return out
}

// conflictingBlocks are nested blocks generate-config-out emits ALONGSIDE a
// mutually-exclusive sibling it also emits: an aws_lb gets both `subnet_mapping {…}`
// blocks AND `subnets = [...]`, which conflict ("only one of … can be specified").
// subnets is the simpler/authoritative form, so the subnet_mapping blocks are dropped.
var conflictingBlocks = map[string]bool{"subnet_mapping": true}

// dropOverEmitLists removes every conflicting nested block (flat body, closed by the
// first `}` at its level) that generate-config-out over-emits.
func dropOverEmitLists(lines []string) []string {
	out := make([]string, 0, len(lines))
	for i := 0; i < len(lines); i++ {
		t := strings.TrimSpace(lines[i])
		if name := strings.TrimSpace(strings.TrimSuffix(t, "{")); strings.HasSuffix(t, "{") && conflictingBlocks[name] {
			for i++; i < len(lines) && strings.TrimSpace(lines[i]) != "}"; i++ {
			}
			continue // skip block including its closing "}"
		}
		out = append(out, lines[i])
	}
	return out
}

// hclTagsBlock renders a resource's tags as an indented HCL `tags = { … }` block
// (keys sorted for deterministic output), or "" when there are none. Used by
// natively-authored resources so an import plan doesn't propose stripping live tags.
func hclTagsBlock(tags map[string]string, indent string) string {
	if len(tags) == 0 {
		return ""
	}
	keys := make([]string, 0, len(tags))
	for k := range tags {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	fmt.Fprintf(&b, "%stags = {\n", indent)
	for _, k := range keys {
		// Escape ${ / %{ so an API-supplied tag key or value can't inject a Terraform
		// template expression (e.g. a tag literally named `${file("~/.aws/credentials")}`).
		fmt.Fprintf(&b, "%s  %q = %q\n", indent, util.EscapeHCLTemplate(k), util.EscapeHCLTemplate(tags[k]))
	}
	fmt.Fprintf(&b, "%s}\n", indent)
	return b.String()
}

// authorKeyPairs authors aws_key_pair resources directly. generate-config-out
// drops them (public_key is write-only in the provider schema, so it can't read it
// back), leaving them a coverage gap and any instance's key_name reference dangling.
// Resource Explorer reports a key pair by its ID (key-…), not its name, so fetch by
// --key-pair-ids to get the real KeyName + PublicKey, author a real block, register
// the KeyName for cross-reference rewiring, and correct the import id (a key pair
// imports by name, not id). Returns the count authored.
func authorKeyPairs(ctx context.Context, path, region string, items []*model.Resource, addrs []string, crossRef map[string][]refTarget) int {
	declared := declaredAddrs(path)
	var b strings.Builder
	n := 0
	for i, r := range items {
		if r.NativeType != "ec2:key-pair" || declared[addrs[i]] {
			continue // skip if generate-config-out already emitted it (avoid a duplicate)
		}
		reg := r.Location
		if reg == "" {
			reg = region
		}
		var kp struct{ Name, Pub string }
		_ = runAws(ctx, &kp, "ec2", "describe-key-pairs", "--key-pair-ids", r.Name,
			"--include-public-key", "--region", reg, "--query", "KeyPairs[0].{Name:KeyName,Pub:PublicKey}")
		if kp.Name == "" || kp.Pub == "" {
			continue
		}
		label := addrs[i]
		if dot := strings.LastIndex(label, "."); dot >= 0 {
			label = label[dot+1:]
		}
		// public_key is write-only: an import doesn't read it back, so without
		// ignore_changes the config value "forces replacement" on adoption. Ignored on
		// import (no replace); still used on a from-scratch create. Tags come from the
		// enumerated resource so an import plan doesn't propose stripping the live tags.
		// key_name is an API string (≤255 arbitrary chars) — escape ${ / %{ so it can't
		// inject a Terraform template expression evaluated at plan time.
		fmt.Fprintf(&b, "\nresource \"aws_key_pair\" %q {\n  key_name   = %q\n  public_key = %q\n%s  lifecycle { ignore_changes = [public_key] }\n}\n", label, util.EscapeHCLTemplate(kp.Name), strings.TrimSpace(kp.Pub), hclTagsBlock(r.Tags, "  "))
		crossRef["aws_key_pair"] = append(crossRef["aws_key_pair"], refTarget{addr: addrs[i], name: kp.Name})
		if r.Properties == nil {
			r.Properties = map[string]any{}
		}
		r.Properties["tl_keyname"] = kp.Name // so the reconcile's deriveImportID imports by name
		n++
	}
	if n > 0 {
		if f, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0o644); err == nil {
			_, _ = f.WriteString(b.String())
			_ = f.Close()
		}
	}
	return n
}

// authorListeners authors aws_lb_listener resources directly. generate-config-out
// drops them (a gap), which leaves a target group with no load-balancer association
// so any ECS service using it fails to create. describe-listeners returns the
// config; the load_balancer_arn / target_group_arn are emitted literally and later
// rewired to references. Returns the authored listener addresses.
func authorListeners(ctx context.Context, path, region string, items []*model.Resource, addrs []string) []string {
	declared := declaredAddrs(path)
	var b strings.Builder
	var authored []string
	for i, r := range items {
		if !strings.HasPrefix(r.NativeType, "elasticloadbalancing:listener") || declared[addrs[i]] {
			continue
		}
		reg := r.Location
		if reg == "" {
			reg = region
		}
		var l struct {
			Port            int    `json:"Port"`
			Protocol        string `json:"Protocol"`
			LoadBalancerArn string `json:"LoadBalancerArn"`
			DefaultActions  []struct {
				Type           string `json:"Type"`
				TargetGroupArn string `json:"TargetGroupArn"`
			} `json:"DefaultActions"`
		}
		if err := runAws(ctx, &l, "elbv2", "describe-listeners", "--listener-arns", r.ID, "--region", reg, "--query", "Listeners[0]"); err != nil || l.LoadBalancerArn == "" {
			continue
		}
		label := addrs[i]
		if dot := strings.LastIndex(label, "."); dot >= 0 {
			label = label[dot+1:]
		}
		fmt.Fprintf(&b, "\nresource \"aws_lb_listener\" %q {\n  load_balancer_arn = %q\n  port     = %d\n  protocol = %q\n", label, l.LoadBalancerArn, l.Port, l.Protocol)
		for _, a := range l.DefaultActions {
			if a.Type == "forward" && a.TargetGroupArn != "" {
				fmt.Fprintf(&b, "  default_action {\n    type             = \"forward\"\n    target_group_arn = %q\n  }\n", a.TargetGroupArn)
			}
		}
		b.WriteString("}\n")
		authored = append(authored, addrs[i])
	}
	if len(authored) > 0 {
		if f, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0o644); err == nil {
			_, _ = f.WriteString(b.String())
			_ = f.Close()
		}
	}
	return authored
}

// addEcsListenerDeps makes every aws_ecs_service that attaches to a load balancer
// depend on all authored listeners, so the target-group→LB association exists before
// the service is created ("target group does not have an associated load balancer").
func addEcsListenerDeps(path string, listeners []string) {
	if len(listeners) == 0 {
		return
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return
	}
	dep := "  depends_on = [" + strings.Join(listeners, ", ") + "]\n"
	lines := strings.Split(string(data), "\n")
	var out []string
	for i := 0; i < len(lines); i++ {
		m := resHeaderRe.FindStringSubmatch(lines[i])
		if m == nil || m[1] != "aws_ecs_service" {
			out = append(out, lines[i])
			continue
		}
		depth, end := hcl.BraceDelta(lines[i]), i
		for j := i + 1; j < len(lines); j++ {
			depth += hcl.BraceDelta(lines[j])
			if depth <= 0 {
				end = j
				break
			}
		}
		block := lines[i:end] // header .. line before closing brace
		if anyMatches(block, regexp.MustCompile(`load_balancer\s*\{`)) {
			out = append(out, block...)
			out = append(out, strings.TrimRight(dep, "\n"))
			out = append(out, lines[end])
		} else {
			out = append(out, lines[i:end+1]...)
		}
		i = end
	}
	_ = os.WriteFile(path, []byte(strings.Join(out, "\n")), 0o644)
}

// authorTaskDefs authors aws_ecs_task_definition resources directly.
// generate-config-out cannot emit them (it drops them to a gap), which dangles any
// ECS service's task_definition reference. describe-task-definition returns the full
// definition, so re-author it (control-plane: container_definitions may carry env
// config, which ships and is flagged by the secrets review, per ADR-001). The
// import id is the task-definition ARN. Returns the count authored.
func authorTaskDefs(ctx context.Context, path, region string, items []*model.Resource, addrs []string) int {
	declared := declaredAddrs(path)
	var b strings.Builder
	n := 0
	for i, r := range items {
		if r.NativeType != "ecs:task-definition" || declared[addrs[i]] {
			continue // skip if generate-config-out already emitted it (avoid a duplicate)
		}
		reg := r.Location
		if reg == "" {
			reg = region
		}
		var td struct {
			Family                  string          `json:"family"`
			TaskRoleArn             string          `json:"taskRoleArn"`
			ExecutionRoleArn        string          `json:"executionRoleArn"`
			NetworkMode             string          `json:"networkMode"`
			Cpu                     string          `json:"cpu"`
			Memory                  string          `json:"memory"`
			RequiresCompatibilities []string        `json:"requiresCompatibilities"`
			ContainerDefinitions    json.RawMessage `json:"containerDefinitions"`
		}
		if err := runAws(ctx, &td, "ecs", "describe-task-definition", "--task-definition", r.Name, "--region", reg, "--query", "taskDefinition"); err != nil || td.Family == "" {
			continue
		}
		var compact bytes.Buffer
		if json.Compact(&compact, td.ContainerDefinitions) != nil {
			continue
		}
		// Escape Terraform interpolation sequences so an env value like "${X}" in the
		// JSON is treated literally inside the heredoc.
		cdefs := strings.ReplaceAll(strings.ReplaceAll(compact.String(), "${", "$${"), "%{", "%%{")

		label := addrs[i]
		if dot := strings.LastIndex(label, "."); dot >= 0 {
			label = label[dot+1:]
		}
		fmt.Fprintf(&b, "\nresource \"aws_ecs_task_definition\" %q {\n  family = %q\n", label, td.Family)
		if td.NetworkMode != "" {
			fmt.Fprintf(&b, "  network_mode = %q\n", td.NetworkMode)
		}
		if len(td.RequiresCompatibilities) > 0 {
			fmt.Fprintf(&b, "  requires_compatibilities = %q\n", td.RequiresCompatibilities)
		}
		if td.Cpu != "" {
			fmt.Fprintf(&b, "  cpu = %q\n", td.Cpu)
		}
		if td.Memory != "" {
			fmt.Fprintf(&b, "  memory = %q\n", td.Memory)
		}
		if td.ExecutionRoleArn != "" {
			fmt.Fprintf(&b, "  execution_role_arn = %q\n", td.ExecutionRoleArn)
		}
		if td.TaskRoleArn != "" {
			fmt.Fprintf(&b, "  task_role_arn = %q\n", td.TaskRoleArn)
		}
		fmt.Fprintf(&b, "  container_definitions = <<-CONTAINERS\n  %s\n  CONTAINERS\n}\n", cdefs)
		n++
	}
	if n > 0 {
		if f, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0o644); err == nil {
			_, _ = f.WriteString(b.String())
			_ = f.Close()
		}
	}
	return n
}

// declaredAddrs returns the "type.name" addresses already present in the file, so
// the native authors don't emit a duplicate of a resource generate-config-out did
// manage to produce (its output is not fully deterministic across runs).
func declaredAddrs(path string) map[string]bool {
	out := map[string]bool{}
	data, err := os.ReadFile(path)
	if err != nil {
		return out
	}
	for _, m := range resourceLabelRe.FindAllStringSubmatch(string(data), -1) {
		out[m[1]+"."+m[2]] = true
	}
	return out
}

// refTarget is one exported resource, indexed so cross-references to it can be
// rewired to a Terraform reference (needed for greenfield re-apply: literal
// names/ARNs/revisions don't exist after a destroy/rebuild).
type refTarget struct {
	addr, name, id, arn string
}

// crossRefRule rewrites a specific reference ATTRIBUTE (never a bare name, which
// would self-reference a resource's own `name`) to the target resource's attribute.
type crossRefRule struct {
	attr, targetType, targetAttr string
	re                           *regexp.Regexp // compiled once (init); matches `attr = "…"`
}

var awsCrossRefRules = []crossRefRule{
	{attr: "task_definition", targetType: "aws_ecs_task_definition", targetAttr: "arn"},
	{attr: "event_bus_name", targetType: "aws_cloudwatch_event_bus", targetAttr: "name"},
	{attr: "key_name", targetType: "aws_key_pair", targetAttr: "key_name"},
	{attr: "key_id", targetType: "aws_kms_key", targetAttr: "key_id"},
	{attr: "kms_key_id", targetType: "aws_kms_key", targetAttr: "arn"},
	{attr: "kms_master_key_id", targetType: "aws_kms_key", targetAttr: "arn"},
	{attr: "target_group_arn", targetType: "aws_lb_target_group", targetAttr: "arn"},
	{attr: "load_balancer_arn", targetType: "aws_lb", targetAttr: "arn"},
}

func init() { // precompile each rule's line matcher once, not per (line × rule)
	for i := range awsCrossRefRules {
		r := &awsCrossRefRules[i]
		r.re = regexp.MustCompile(`^(\s*)` + regexp.QuoteMeta(r.attr) + `(\s*)=\s*"([^"]+)"\s*(#.*)?$`)
	}
}

// rewireCrossRefs rewrites literal cross-resource references (by name, ARN, or
// name:revision) to Terraform references, so the repo re-applies from scratch with
// correct ordering and post-rebuild ids. Attribute-scoped so a resource's own
// `name = "x"` is never turned into a self-reference. Returns the count rewired.
func rewireCrossRefs(path string, byType map[string][]refTarget) int {
	data, err := os.ReadFile(path)
	if err != nil {
		return 0
	}
	src := string(data)
	// Only rewire to a target whose resource block is ACTUALLY DECLARED here: a
	// referenced resource that generate-config-out dropped to a gap (e.g. an ECS
	// task definition it couldn't emit) is not declared, and pointing at it yields
	// "Reference to undeclared resource".
	declared := map[string]bool{}
	for _, m := range resourceLabelRe.FindAllStringSubmatch(src, -1) {
		declared[m[1]+"."+m[2]] = true
	}
	lines := strings.Split(src, "\n")
	n := 0
	curType := "" // resource type of the block being scanned
	for i, l := range lines {
		if m := resHeaderRe.FindStringSubmatch(l); m != nil {
			curType = m[1]
			continue
		}
		for _, rule := range awsCrossRefRules {
			if curType == rule.targetType {
				continue // inside the target type itself: `key_name` here is its OWN name, not a reference
			}
			m := rule.re.FindStringSubmatch(l)
			if m == nil {
				continue
			}
			t := matchTarget(byType[rule.targetType], m[3])
			if t == nil || !declared[t.addr] {
				break // no exported+declared target (AWS-managed key, or a gapped resource) — leave literal
			}
			lines[i] = m[1] + rule.attr + m[2] + "= " + t.addr + "." + rule.targetAttr
			n++
			break
		}
	}
	if n > 0 {
		_ = os.WriteFile(path, []byte(strings.Join(lines, "\n")), 0o644)
	}
	return n
}

// matchTarget resolves a literal reference value to an exported resource: exact
// name, exact id/ARN, or a "name:revision" whose name matches (ECS task defs).
func matchTarget(targets []refTarget, val string) *refTarget {
	nameOnly := val
	if i := strings.Index(val, ":"); i > 0 && !strings.HasPrefix(val, "arn:") {
		nameOnly = val[:i] // "family:revision" -> "family"
	}
	for i := range targets {
		t := &targets[i]
		if val == t.name || val == t.id || val == t.arn || nameOnly == t.name {
			return t
		}
	}
	return nil
}

func anyMatches(lines []string, re *regexp.Regexp) bool {
	for _, l := range lines {
		if re.MatchString(l) {
			return true
		}
	}
	return false
}

func tail(s string, lines int) string {
	parts := strings.Split(strings.TrimRight(s, "\n"), "\n")
	if len(parts) > lines {
		parts = parts[len(parts)-lines:]
	}
	return strings.Join(parts, "\n")
}
