package github

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/cyberproaustin/terralift/internal/core"
	"github.com/cyberproaustin/terralift/internal/hcl"
	"github.com/cyberproaustin/terralift/internal/model"
	"github.com/cyberproaustin/terralift/internal/naming"
	"github.com/cyberproaustin/terralift/internal/provider"
	"github.com/cyberproaustin/terralift/internal/tf"
)

// export produces born-correct import blocks + a providers.tf, then drafts config
// via `terraform plan -generate-config-out` and keeps only the import blocks whose
// config actually generated (the rest are honest gaps). One flat container: the
// org/user login.
func export(ctx context.Context, run *core.Run, inv *model.Inventory) (*provider.ExportResult, error) {
	owner := run.Scope.ID
	dir := filepath.Join(run.Paths.Export, naming.Sanitize(owner))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}

	ids := make([]string, 0, len(inv.Resources))
	for id := range inv.Resources {
		ids = append(ids, id)
	}
	sort.Strings(ids) // deterministic order -> stable born-correct suffixes

	type item struct {
		res      *model.Resource
		importID string
	}
	var items []item
	var addrs []naming.Address
	var gap []string
	for _, id := range ids {
		r := inv.Resources[id]
		if r.TFType == "" { // no TF mapping -> genuine coverage gap
			gap = append(gap, r.ID)
			continue
		}
		items = append(items, item{res: r, importID: deriveImportID(r)})
		addrs = append(addrs, naming.Address{Type: r.TFType, Base: naming.Sanitize(r.Name)})
	}
	names := naming.Dedupe(addrs) // born-correct, de-collided addresses

	itemAddr := make([]string, len(items))
	var b strings.Builder
	b.WriteString("# Generated by TerraLift — born-correct import blocks.\n")
	b.WriteString("# `terraform apply` imports these into state at the chosen addresses.\n\n")
	for i, it := range items {
		itemAddr[i] = it.res.TFType + "." + names[i]
		b.WriteString(hcl.ImportBlock(itemAddr[i], it.importID))
	}
	if err := os.WriteFile(filepath.Join(dir, "import.tf"), []byte(b.String()), 0o644); err != nil {
		return nil, err
	}

	// providers.tf: owner covers both org and user logins; auth is via the
	// GITHUB_TOKEN env var (set in connect), never inlined into config.
	prov := fmt.Sprintf(`terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 6.0"
    }
  }
}

provider "github" {
  owner = %q
  # Auth via the GITHUB_TOKEN environment variable (never inline a token in config).
}
`, owner)
	_ = os.WriteFile(filepath.Join(dir, "providers.tf"), []byte(prov), 0o644)

	run.Log.Info("Export", "%d resource import blocks (%d gap) -> %s", len(items), len(gap), dir)

	mode := "import"
	if run.Config.HCLOnly {
		mode = "hcl-only"
	}

	// --- terraform init + generate-config-out (draft HCL; experimental) ---
	var redactions []hcl.Redaction
	r := tf.New(dir)
	if out, err := r.Init(ctx); err != nil {
		run.Log.Warn("Export", "terraform init failed: %v", err)
		run.Log.Verbose("Export", "%s", hcl.Tail(out, 20))
	} else {
		gen := filepath.Join(dir, "generated.tf")
		_, genErr := r.GenerateConfig(ctx, gen)
		if _, statErr := os.Stat(gen); statErr == nil {
			pruned := pruneGeneratedHCL(gen)
			authored := authorRepoAttrs(gen, repoHasDownloads(inv))
			redactions = scrubGeneratedHCL(gen)
			note := ""
			if genErr != nil {
				note = " (raw had over-emit warnings)"
			}
			run.Log.Info("Export", "generated draft HCL%s: %d pruned, %d authored, %d scrubbed -> %s", note, pruned, authored, len(redactions), gen)
		} else {
			run.Log.Warn("Export", "generate-config-out produced no HCL: %v", genErr)
		}
	}

	// Keep only import blocks whose config actually generated; the rest are gaps.
	generated := hcl.ScanAddrsFile(filepath.Join(dir, "generated.tf"))
	cands := make([]hcl.ImportCandidate, len(items))
	for i, it := range items {
		cands[i] = hcl.ImportCandidate{Addr: itemAddr[i], ImportID: it.importID}
	}
	mappedIdx, gapIdx, _ := hcl.SplitByGenerated(filepath.Join(dir, "import.tf"), hcl.ImportHeader, generated, cands)

	mapped := make([]string, 0, len(mappedIdx))
	refByID := make(map[string]string, len(mappedIdx))
	for _, i := range mappedIdx {
		it := items[i]
		mapped = append(mapped, it.res.ID)
		refByID[it.res.ID] = itemAddr[i] + ".id"
	}
	for _, i := range gapIdx {
		gap = append(gap, items[i].res.ID)
	}
	if len(gapIdx) > 0 {
		run.Log.Info("Export", "dropped %d import block(s) with no generated config", len(gapIdx))
	}

	return &provider.ExportResult{
		Mode: mode,
		Containers: []provider.ContainerExport{{
			Container: owner, Dir: dir, MappedIDs: mapped,
			GapIDs: gap, AddressByID: refByID,
			ConfigFiles: []string{"generated.tf"}, Redactions: redactions,
		}},
	}, nil
}
