package hcl

import (
	"fmt"
	"os"
	"strings"
)

// ImportHeader is the standard first line of a generated import.tf.
const ImportHeader = "# Generated by TerraLift — born-correct import blocks.\n\n"

// ImportBlock renders one Terraform `import {}` block adopting the resource at
// address addr with import id. Every provider emitted this exact shape by hand;
// callers that must protect the id from template interpolation should pass an
// already-escaped id (see util.EscapeHCLTemplate) — the %q verb only escapes
// quotes and backslashes, not ${ } / %{ } sequences.
func ImportBlock(addr, id string) string {
	return fmt.Sprintf("import {\n  to = %s\n  id = %q\n}\n\n", addr, id)
}

// ImportCandidate is one resource considered for adoption: its config address
// (`type.name`) and the import id to write if it is kept.
type ImportCandidate struct {
	Addr, ImportID string
}

// SplitByGenerated partitions cands into mapped (Addr present in generated) and
// gap (Addr absent — `terraform plan -generate-config-out` produced no matching
// config, so an import block for it would fail plan with "Configuration for
// import target does not exist"). It rewrites path to header plus one import
// block per MAPPED candidate, so no orphan import block is left behind — this
// includes the all-gap case (header only), reported honestly rather than as a
// silent 100%. Returns the mapped and gap indices in candidate order.
//
// This is the shared reconcile-against-generated step that AWS and GCP each
// hand-rolled; provider-specific bookkeeping (gap/mapped id lists, reference
// maps) stays in the caller, keyed off the returned indices.
func SplitByGenerated(path, header string, generated map[string]bool, cands []ImportCandidate) (mapped, gap []int, err error) {
	var b strings.Builder
	b.WriteString(header)
	for i, c := range cands {
		if generated[c.Addr] {
			mapped = append(mapped, i)
			b.WriteString(ImportBlock(c.Addr, c.ImportID))
		} else {
			gap = append(gap, i)
		}
	}
	return mapped, gap, os.WriteFile(path, []byte(b.String()), 0o644)
}
