package hcl

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSplitByGenerated(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "import.tf")
	generated := map[string]bool{"aws_vpc.a": true, "aws_subnet.b": true} // aws_eip.c NOT generated
	cands := []ImportCandidate{
		{Addr: "aws_vpc.a", ImportID: "vpc-1"},
		{Addr: "aws_eip.c", ImportID: "eipalloc-9"}, // gap: no generated config
		{Addr: "aws_subnet.b", ImportID: "subnet-2"},
	}
	mapped, gap, err := SplitByGenerated(path, ImportHeader, generated, cands)
	if err != nil {
		t.Fatal(err)
	}
	if len(mapped) != 2 || mapped[0] != 0 || mapped[1] != 2 {
		t.Errorf("mapped indices = %v, want [0 2]", mapped)
	}
	if len(gap) != 1 || gap[0] != 1 {
		t.Errorf("gap indices = %v, want [1]", gap)
	}
	data, _ := os.ReadFile(path)
	out := string(data)
	if !strings.Contains(out, "id = \"vpc-1\"") || !strings.Contains(out, "id = \"subnet-2\"") {
		t.Errorf("import.tf missing kept blocks:\n%s", out)
	}
	if strings.Contains(out, "eipalloc-9") {
		t.Errorf("import.tf kept an orphan (ungenerated) block:\n%s", out)
	}
}

func TestSplitByGeneratedAllGap(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "import.tf")
	cands := []ImportCandidate{{Addr: "x.y", ImportID: "id1"}}
	mapped, gap, err := SplitByGenerated(path, ImportHeader, map[string]bool{}, cands)
	if err != nil {
		t.Fatal(err)
	}
	if len(mapped) != 0 || len(gap) != 1 {
		t.Errorf("all-gap: mapped=%v gap=%v, want [] [0]", mapped, gap)
	}
	// import.tf is still written (header only), never left with an orphan block.
	data, _ := os.ReadFile(path)
	if !strings.HasPrefix(string(data), "# Generated by TerraLift") || strings.Contains(string(data), "import {") {
		t.Errorf("all-gap import.tf should be header-only:\n%s", string(data))
	}
}
