package gcp

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/cyberproaustin/terralift/internal/core"
	"github.com/cyberproaustin/terralift/internal/hcl"
	"github.com/cyberproaustin/terralift/internal/model"
	"github.com/cyberproaustin/terralift/internal/naming"
	"github.com/cyberproaustin/terralift/internal/provider"
	"github.com/cyberproaustin/terralift/internal/tf"
)

// export produces born-correct Terraform for the enumerated inventory:
//  1. classify each resource: export (user-managed, mappable) / exclude
//     (GCP-managed default, sub-resource, noise) / gap (unsupported type),
//  2. derive each exported resource's import ID from its CAI asset name,
//  3. author native `import { to = google_x.<real-name>; id = ... }` blocks — WE
//     control the address, so names are born correct (naming.Dedupe),
//  4. `terraform init` + `plan -generate-config-out` to draft the HCL,
//  5. scrub any leaked sensitive values from the generated draft.
func export(ctx context.Context, run *core.Run, inv *model.Inventory) (*provider.ExportResult, error) {
	projectID := naming.Sanitize(run.Scope.ID) // path-safe; scope id is an operator flag
	dir := filepath.Join(run.Paths.Export, projectID)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}

	// Deterministic order by canonical id so born-correct suffixes are stable.
	ids := make([]string, 0, len(inv.Resources))
	for id := range inv.Resources {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	type item struct {
		res      *model.Resource
		importID string
	}
	var items []item
	var addrs []naming.Address
	var excluded, gap []string
	ex := computeExclusions(inv) // MIG members + instance boot disks to drop
	for _, id := range ids {
		r := inv.Resources[id]
		if reason := excludedReason(r, ex); reason != "" { // GCP-managed / default / sub-resource / noise
			excluded = append(excluded, r.ID)
			continue
		}
		if r.TFType == "" { // no TF mapping -> genuine coverage gap
			gap = append(gap, r.ID)
			continue
		}
		items = append(items, item{res: r, importID: deriveImportID(r.ID, r.TFType, run.Scope.ID)})
		addrs = append(addrs, naming.Address{Type: r.TFType, Base: naming.Sanitize(r.Name)})
	}
	names := naming.Dedupe(addrs) // born-correct, de-collided addresses

	// --- born-correct import blocks + address maps ---
	// addrByID (bare "type.name") is for IAM owner-resolution, which appends its own
	// attribute (.name/.id). refByID (full reference expression) is for cross-reference
	// rewiring and is built below, only for resources whose config actually generated.
	addrByID := make(map[string]string, len(items))
	itemAddr := make([]string, len(items))
	var b strings.Builder
	b.WriteString("# Generated by TerraLift — born-correct import blocks.\n")
	b.WriteString("# `terraform apply` imports these into state at the chosen addresses.\n\n")
	for i, it := range items {
		addr := it.res.TFType + "." + names[i]
		itemAddr[i] = addr
		addrByID[it.res.ID] = addr // CAI-asset-name form; IAM scopes match this
		b.WriteString(hcl.ImportBlock(addr, it.importID))
	}
	if err := os.WriteFile(filepath.Join(dir, "import.tf"), []byte(b.String()), 0o644); err != nil {
		return nil, err
	}

	// --- providers.tf ---
	prov := fmt.Sprintf(`terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 7.0"
    }
  }
}

provider "google" {
  project = %q

  # Adopt existing resources without mutating them: the provider otherwise stamps
  # every managed resource with a goog-terraform-provisioned=true label, which on
  # import shows up as a spurious in-place change to terraform_labels. Onboarding
  # must not modify live infrastructure just by bringing it under management.
  add_terraform_attribution_label = false
}
`, run.Scope.ID)
	_ = os.WriteFile(filepath.Join(dir, "providers.tf"), []byte(prov), 0o644)

	run.Log.Info("Export", "%d resource import blocks (%d excluded, %d gap) -> %s", len(items), len(excluded), len(gap), dir)

	mode := "import"
	if run.Config.HCLOnly {
		mode = "hcl-only"
	}

	// --- terraform init + generate-config-out (draft HCL; experimental) ---
	var redactions []hcl.Redaction
	r := tf.New(dir)
	if out, err := r.Init(ctx); err != nil {
		run.Log.Warn("Export", "terraform init failed: %v", err)
		run.Log.Verbose("Export", "%s", hcl.Tail(out, 20))
	} else {
		gen := filepath.Join(dir, "generated.tf")
		out, genErr := r.GenerateConfig(ctx, gen)
		// terraform writes generated.tf even when it reports over-emit errors
		// (conflicting/invalid defaults), so prune + scrub whenever it exists.
		if _, statErr := os.Stat(gen); statErr == nil {
			pruned := pruneGeneratedHCL(gen)
			redactions = scrubGeneratedHCL(gen)
			note := ""
			if genErr != nil {
				note = " (raw had over-emit warnings)"
			}
			run.Log.Info("Export", "generated draft HCL%s: %d over-emitted pruned, %d scrubbed -> %s", note, pruned, len(redactions), gen)
		} else {
			run.Log.Warn("Export", "generate-config-out produced no HCL: %v", genErr)
			run.Log.Verbose("Export", "%s", hcl.Tail(out, 30))
		}
	}

	// Reconcile: an import block is only usable if generate-config-out actually
	// emitted matching config. Any address absent from generated.tf is a gap —
	// this INCLUDES the case where generation produced nothing at all (init/plan
	// failed), which must be reported honestly as all-gap, never silently as 100%
	// mapped over an unusable artifact. (An orphan import block with no config also
	// fails `terraform plan` with "Configuration for import target does not exist".)
	generated := hcl.ScanAddrsFile(filepath.Join(dir, "generated.tf"))
	cands := make([]hcl.ImportCandidate, len(items))
	for i, it := range items {
		cands[i] = hcl.ImportCandidate{Addr: itemAddr[i], ImportID: it.importID}
	}
	// Shared reconcile: keep only import blocks whose config actually generated,
	// rewrite import.tf to those, and get back the mapped/gap partition.
	mappedIdx, gapIdx, _ := hcl.SplitByGenerated(filepath.Join(dir, "import.tf"), hcl.ImportHeader, generated, cands)

	mapped := make([]string, 0, len(mappedIdx))
	// refByID: literal id -> full Terraform reference. Each id FORM resolves to a
	// different attribute so a rewired clone points at the right one: a CAI asset name
	// or projects/... path -> .id; a self-link URL -> .self_link; a service-account
	// email -> .email; a static IP -> .address. Built only for MAPPED resources (so no
	// dangling reference to a dropped resource is emitted).
	refByID := make(map[string]string, len(mappedIdx))
	for _, i := range mappedIdx {
		it := items[i]
		mapped = append(mapped, it.res.ID)
		addr := itemAddr[i]
		refByID[it.res.ID] = addr + ".id"
		if strings.HasPrefix(it.importID, "projects/") {
			refByID[it.importID] = addr + ".id"
		}
		if sl, _ := it.res.Properties["selfLink"].(string); sl != "" {
			refByID[sl] = addr + ".self_link"
			// The same self-link is emitted under the compute.googleapis.com host in some
			// fields (e.g. a DNS zone's network_url) instead of www.googleapis.com.
			refByID[strings.Replace(sl, "https://www.googleapis.com/compute/", "https://compute.googleapis.com/compute/", 1)] = addr + ".self_link"
		}
		switch it.res.TFType {
		case "google_service_account":
			if email, _ := it.res.Properties["email"].(string); email != "" {
				refByID[email] = addr + ".email"
			}
		case "google_compute_address", "google_compute_global_address":
			if ip, _ := it.res.Properties["address"].(string); ip != "" {
				refByID[ip] = addr + ".address"
			}
		case "google_compute_instance_group_manager", "google_compute_region_instance_group_manager":
			// The MIG owns an instance group we exclude from onboarding; a backend
			// service references that group's URL, so resolve it to the MIG's
			// .instance_group output instead of a dangling standalone resource.
			if ig, _ := it.res.Properties["instanceGroup"].(string); ig != "" {
				refByID[ig] = addr + ".instance_group"
			}
		}
	}
	for _, i := range gapIdx {
		gap = append(gap, items[i].res.ID)
		delete(addrByID, items[i].res.ID)
	}
	if len(gapIdx) > 0 {
		run.Log.Info("Export", "dropped %d import block(s) with no generated config", len(gapIdx))
	}

	// --- user IAM bindings (authored directly; written AFTER the reconcile so IAM
	// import blocks aren't clobbered) ---
	iamHCL, iamImports, iamN := generateIAM(inv, addrByID)
	if iamN > 0 {
		_ = os.WriteFile(filepath.Join(dir, "iam.tf"), []byte(iamHCL), 0o644)
		if fh, err := os.OpenFile(filepath.Join(dir, "import.tf"), os.O_APPEND|os.O_WRONLY, 0o644); err == nil {
			_, _ = fh.WriteString(iamImports)
			_ = fh.Close()
		}
		run.Log.Info("Export", "%d user IAM binding(s) -> iam.tf", iamN)
	}
	return &provider.ExportResult{
		Mode: mode,
		Containers: []provider.ContainerExport{{
			Container: run.Scope.ID, Dir: dir, MappedIDs: mapped,
			ExcludedIDs: excluded, GapIDs: gap, AddressByID: refByID,
			ConfigFiles: []string{"generated.tf"}, Redactions: redactions,
		}},
	}, nil
}

// excludedReason returns a non-empty reason when a resource is intentionally NOT
// an onboarding target: GCP-managed service accounts, auto-created default
// networking, sub-resources, and control-plane noise. These are separated from
// genuine "unsupported type" gaps so the coverage metric stays honest.
func excludedReason(r *model.Resource, ex derivedExclusions) string {
	switch r.NativeType {
	case "serviceusage.googleapis.com/Service":
		return "api-enablement (serviceusage)"
	case "cloudbilling.googleapis.com/ProjectBillingInfo":
		return "billing metadata"
	case "compute.googleapis.com/Project":
		return "compute project metadata"
	case "secretmanager.googleapis.com/SecretVersion":
		return "secret version (data-plane sub-resource)"
	case "cloudkms.googleapis.com/CryptoKeyVersion":
		return "crypto key version (auto-created sub-resource)"
	case "dns.googleapis.com/ResourceRecordSet":
		// The google_dns_record_set import id is {{project}}/{{zone}}/{{name}}/{{type}}
		// but the CAI name carries the numeric zone id, not the zone NAME, so a
		// correct import id can't be derived. Onboard records via their managed zone.
		return "dns record set (import id needs zone name; not derivable from CAI)"
	case "compute.googleapis.com/Route":
		return "auto-created route"
	case "artifactregistry.googleapis.com/DockerImage":
		return "container image artifact (build output, not a Terraform resource)"
	case "run.googleapis.com/Revision":
		return "cloud run revision (service-managed, immutable child of the service)"
	case "dataplex.googleapis.com/EntryGroup":
		// GCP auto-provisions system entry groups (@bigquery, @pubsub, …) for the
		// Dataplex catalog; they are not user-created and have no import target.
		if strings.HasPrefix(lastSegment(r.ID), "@") {
			return "auto-created Dataplex system entry group"
		}
	case "cloudresourcemanager.googleapis.com/Project":
		// Deliberately excludes ALL Project assets, not just the operating one:
		// enumeration is project-scoped so the only Project present IS the operating
		// project, and a google_project imports by its STRING project id, which the
		// CAI name (…/projects/<NUMBER>) doesn't carry — adopting it would produce a
		// wrong import id. Excluding is the safe, honest choice.
		return "project resource (self; string project-id not derivable from CAI)"
	}
	if notImportable(r) {
		return "google-managed service account"
	}
	// Resources the Cloud Functions service provisions on the user's behalf — a
	// gen2 function's backing run.googleapis.com/Service and its gcf-v2-sources
	// staging bucket — carry goog-managed-by=cloudfunctions. Onboard the function
	// once through google_cloudfunctions2_function; drop these so they aren't
	// double-managed as a standalone Cloud Run service / bucket.
	if r.Tags["goog-managed-by"] == "cloudfunctions" {
		return "cloud-functions-managed resource (backing service / source bucket)"
	}
	name := lastSegment(r.ID)
	// An instance created by a managed instance group is cattle owned by the MIG
	// ("<baseInstanceName>-<suffix>"). Managing it standalone would fight the MIG on
	// its next heal/resize; onboard the MIG, not its members.
	if r.NativeType == "compute.googleapis.com/Instance" && migManaged(name, ex.migBases) {
		return "managed instance-group member (managed via its MIG)"
	}
	// A boot disk is created and owned by its instance's boot_disk block; onboarding
	// it standalone would double-manage the same disk. A non-boot data disk (a real
	// google_compute_disk) is not in this set and is onboarded normally.
	if r.NativeType == "compute.googleapis.com/Disk" && ex.bootDisks[name] {
		return "instance boot disk (managed via the instance's boot_disk block)"
	}
	// A MIG creates and owns its instance group; onboarding it standalone double-manages
	// it and dangles a reference to the (excluded) MIG member instances.
	if r.NativeType == "compute.googleapis.com/InstanceGroup" && ex.migGroups[name] {
		return "managed instance group (owned by its MIG)"
	}
	if r.NativeType == "compute.googleapis.com/Network" && name == "default" {
		return "default network"
	}
	if r.NativeType == "compute.googleapis.com/Firewall" && strings.HasPrefix(name, "default-allow-") {
		return "default firewall"
	}
	if r.NativeType == "compute.googleapis.com/Subnetwork" {
		if net, _ := r.Properties["network"].(string); strings.HasSuffix(net, "/networks/default") {
			return "default-network subnetwork"
		}
	}
	return ""
}

// derivedExclusions holds cross-resource signals computed once per export that mark
// resources as owned by another onboarded resource (so they aren't double-managed).
type derivedExclusions struct {
	migBases  map[string]bool // MIG baseInstanceNames — exclude "<base>-<suffix>" members
	migGroups map[string]bool // instance-group names owned by a MIG
	bootDisks map[string]bool // disk names that are an instance's boot disk
}

// computeExclusions scans the inventory for MIG base names, MIG-owned instance
// groups, and instance boot disks.
func computeExclusions(inv *model.Inventory) derivedExclusions {
	ex := derivedExclusions{migBases: map[string]bool{}, migGroups: map[string]bool{}, bootDisks: map[string]bool{}}
	for _, r := range inv.Resources {
		switch r.NativeType {
		case "compute.googleapis.com/InstanceGroupManager":
			if b, _ := r.Properties["baseInstanceName"].(string); b != "" {
				ex.migBases[b] = true
			}
			if ig, _ := r.Properties["instanceGroup"].(string); ig != "" {
				ex.migGroups[lastSegment(ig)] = true // the MIG owns this instance group
			}
		case "compute.googleapis.com/Instance":
			disks, _ := r.Properties["disks"].([]any)
			for _, dd := range disks {
				dm, _ := dd.(map[string]any)
				if boot, _ := dm["boot"].(bool); boot {
					if src, _ := dm["source"].(string); src != "" {
						ex.bootDisks[lastSegment(src)] = true
					}
				}
			}
		}
	}
	return ex
}

// migSuffixRe matches the 4-character random suffix GCP appends to MIG-created
// instance names, so a base name only matches its own members (not a longer
// user-named instance that merely shares the prefix).
var migSuffixRe = regexp.MustCompile(`^[a-z0-9]{4}$`)

// migManaged reports whether an instance name is a MIG member ("<base>-<suffix>").
func migManaged(name string, bases map[string]bool) bool {
	for b := range bases {
		if strings.HasPrefix(name, b+"-") && migSuffixRe.MatchString(name[len(b)+1:]) {
			return true
		}
	}
	return false
}

// notImportable filters GCP-managed service accounts (default / service-agent),
// whose account_id the google_service_account schema rejects.
func notImportable(r *model.Resource) bool {
	if r.TFType != "google_service_account" {
		return false
	}
	email, _ := r.Properties["email"].(string)
	if email == "" {
		email = lastSegment(r.ID)
	}
	switch {
	case strings.Contains(email, "@developer.gserviceaccount.com"),
		strings.Contains(email, "@appspot.gserviceaccount.com"),
		strings.Contains(email, "@cloudservices.gserviceaccount.com"),
		strings.Contains(email, "gcp-sa-"), strings.HasPrefix(email, "service-"):
		return true
	}
	return false
}

// scrubGeneratedHCL blanks out sensitive VALUE attributes that
// -generate-config-out can emit in plaintext. Matched by EXACT attribute name
// (a payload field), NOT any name merely containing a keyword — matching by
// substring wrongly blanks control-plane fields like secret_id / kms_key_name.
// gcpSecretAttrs are exact attribute names carrying data-plane secret material;
// the shared redactor removes them (heredoc-aware — a multi-line private_key_pem
// or credentials blob must not survive in generated.tf).
var gcpSecretAttrs = []string{
	"secret_data", "password", "passphrase", "private_key", "private_key_pem",
	"client_secret", "client_key", "access_token", "auth_token", "sas_token",
	"connection_string", "service_account_key", "credentials", "private_key_id",
}

// gcpRedactRules: app config (Cloud Functions/Run env vars) is intentionally NOT
// redacted — it ships and is flagged in the secrets-review report instead. Only
// the exact-name single secrets above are removed.
var gcpRedactRules []hcl.Rule

func scrubGeneratedHCL(path string) []hcl.Redaction {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	out, events := hcl.Redact(string(data), gcpSecretAttrs, gcpRedactRules)
	if len(events) > 0 {
		_ = os.WriteFile(path, []byte(out), 0o644)
	}
	return events
}

// pruneGeneratedHCL removes attributes that -generate-config-out over-emits with
// unset/default values (null, [], {}). These add nothing, and emitting BOTH sides
// of a mutually-exclusive pair as empty lists (e.g. source_tags = [] and
// source_service_accounts = []) makes terraform reject the config. Removing them
// lets the provider apply its real defaults. `= 0` is NOT pruned: a legitimate
// zero (e.g. google_compute_firewall priority = 0) must be preserved.
var emptyAttr = regexp.MustCompile(`^\s*[A-Za-z0-9_]+\s*=\s*(null|\[\]|\{\})\s*$`)

// overEmitAttr matches google-provider attributes that -generate-config-out emits
// with default values that are INVALID in the resource's actual mode (e.g.
// bgp_always_compare_med is rejected under the default LEGACY best-path mode).
// Dropping them lets the provider apply the correct default.
// maintenance_version is read-only on create ("must not be set"); address is the
// reserved IP literal that isn't allocated on a rebuild (drop it and GCP allocates
// a fresh one — import reads the live IP back into state).
var overEmitAttr = regexp.MustCompile(`^\s*(bgp_always_compare_med|delete_bgp_always_compare_med|default_table_expiration_ms|maintenance_version|address)\s*=`)

// generatedComment: generate-config-out boilerplate, stripped as noise.
var generatedComment = regexp.MustCompile(`^\s*#\s*(__generated__ by Terraform|Please review these resources)`)

// unspecifiedEnumRe matches an attribute generate-config-out over-emits with a
// provider *_UNSPECIFIED enum value, which the schema rejects (the real value is a
// concrete enum member or the attribute is simply left unset).
var unspecifiedEnumRe = regexp.MustCompile(`^\s*[A-Za-z0-9_]+\s*=\s*"[A-Z0-9_]+_UNSPECIFIED"\s*$`)

// zeroOverEmit matches attributes generate-config-out emits as 0 when unset, where
// 0 is out of the schema's valid range (a network_interface vlan must be 2..255).
var zeroOverEmit = regexp.MustCompile(`^\s*(vlan)\s*=\s*0\s*$`)

// mutexZeroOverEmit matches the zeroed half of a mutually-exclusive fixed/percent
// pair that generate-config-out emits in full (e.g. a MIG update_policy sets both
// max_surge_fixed=1 and max_surge_percent=0; the =0 twin ConflictsWith the real
// one). Dropping the =0 line clears the conflict and keeps the meaningful value.
var mutexZeroOverEmit = regexp.MustCompile(`^\s*(max_surge_percent|max_surge_fixed|max_unavailable_percent|max_unavailable_fixed)\s*=\s*0\s*$`)

// rpoDefaultOverEmit matches a storage bucket's rpo = "DEFAULT" — the schema default,
// which generate-config-out emits for every bucket but which a REGION (single-region)
// bucket REJECTS at create time (rpo applies only to dual/multi-region buckets).
// Dropping the default keeps recreation valid; a non-default rpo (ASYNC_TURBO) is kept.
var rpoDefaultOverEmit = regexp.MustCompile(`^\s*rpo\s*=\s*"DEFAULT"\s*$`)

// overEmitBlocks are optional nested blocks generate-config-out emits fully
// disabled/zeroed (e.g. a Cloud SQL read_pool_auto_scale_config with enabled=false
// and node counts = 0, which fail the 1..20 range check). Dropping the block lets
// the provider use real defaults.
var overEmitBlocks = map[string]bool{"read_pool_auto_scale_config": true}

// gcpPruneRules are the line-level over-emit patterns hcl.Prune drops from the
// generated HCL. Each regex documents its own rationale above; the mechanism
// (drop any line matching any rule) is shared across providers.
var gcpPruneRules = []*regexp.Regexp{
	emptyAttr, overEmitAttr, unspecifiedEnumRe, zeroOverEmit,
	mutexZeroOverEmit, rpoDefaultOverEmit, generatedComment,
}

func pruneGeneratedHCL(path string) int {
	data, err := os.ReadFile(path)
	if err != nil {
		return 0
	}
	// Block-level pre-passes (brace-balanced) run first, then the shared line filter.
	lines := dropBootDiskSource(hcl.DropBlocksByName(strings.Split(string(data), "\n"), overEmitBlocks))
	out, n := hcl.Prune(strings.Join(lines, "\n"), gcpPruneRules)
	if n > 0 {
		_ = os.WriteFile(path, []byte(out), 0o644)
	}
	return n
}

// dropBootDiskSource drops the `source` attribute inside a boot_disk block that
// ALSO has initialize_params — generate-config-out emits both, which conflict
// ("Cannot specify both 'source' and 'initializeParams'"). Keeping initialize_params
// (the image) is create-friendly and reconciles on import.
func dropBootDiskSource(lines []string) []string {
	out := make([]string, 0, len(lines))
	for i := 0; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) != "boot_disk {" {
			out = append(out, lines[i])
			continue
		}
		depth, j := 1, i+1
		hasInit, srcIdx := false, -1
		for ; j < len(lines) && depth > 0; j++ {
			t := strings.TrimSpace(lines[j])
			if strings.HasPrefix(t, "initialize_params") {
				hasInit = true
			}
			if strings.HasPrefix(t, "source ") || strings.HasPrefix(t, "source=") {
				srcIdx = j
			}
			depth += strings.Count(lines[j], "{") - strings.Count(lines[j], "}")
		}
		out = append(out, lines[i])
		for k := i + 1; k < j; k++ {
			if hasInit && k == srcIdx {
				continue
			}
			out = append(out, lines[k])
		}
		i = j - 1
	}
	return out
}

// (dropOverEmitBlocks was extracted to hcl.DropBlocksByName.)
