package gcp

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/cyberproaustin/terralift/internal/core"
	"github.com/cyberproaustin/terralift/internal/model"
	"github.com/cyberproaustin/terralift/internal/naming"
	"github.com/cyberproaustin/terralift/internal/provider"
	"github.com/cyberproaustin/terralift/internal/tf"
)

// export produces born-correct Terraform for the enumerated inventory:
//  1. derive each resource's import ID from its CAI asset name (per-type table),
//  2. author native `import { to = google_x.<real-name>; id = ... }` blocks — WE
//     control the address, so names are born correct (reusing naming.Dedupe),
//  3. `terraform init` + `plan -generate-config-out` to draft the HCL,
//  4. scrub any leaked sensitive values from the generated draft.
func export(ctx context.Context, run *core.Run, inv *model.Inventory) (*provider.ExportResult, error) {
	projectID := run.Scope.ID
	dir := filepath.Join(run.Paths.Export, projectID)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}

	// Deterministic order by canonical id so born-correct suffixes are stable.
	ids := make([]string, 0, len(inv.Resources))
	for id := range inv.Resources {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	type item struct {
		res      *model.Resource
		importID string
	}
	var items []item
	var addrs []naming.Address
	var unmapped []string
	for _, id := range ids {
		r := inv.Resources[id]
		if r.TFType == "" { // unmapped -> honest coverage gap, no import block
			unmapped = append(unmapped, r.ID)
			continue
		}
		if notImportable(r) { // Google-managed resource, not a user import target
			unmapped = append(unmapped, r.ID)
			continue
		}
		items = append(items, item{res: r, importID: deriveImportID(r.ID, r.TFType, projectID)})
		addrs = append(addrs, naming.Address{Type: r.TFType, Base: naming.Sanitize(r.Name)})
	}
	names := naming.Dedupe(addrs) // born-correct, de-collided addresses

	// --- born-correct import blocks ---
	var b strings.Builder
	b.WriteString("# Generated by TerraLift — born-correct import blocks.\n")
	b.WriteString("# `terraform apply` imports these into state at the chosen addresses.\n\n")
	for i, it := range items {
		fmt.Fprintf(&b, "import {\n  to = %s.%s\n  id = %q\n}\n\n", it.res.TFType, names[i], it.importID)
	}
	if err := os.WriteFile(filepath.Join(dir, "import.tf"), []byte(b.String()), 0o644); err != nil {
		return nil, err
	}

	// --- providers.tf ---
	prov := fmt.Sprintf(`terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 7.0"
    }
  }
}

provider "google" {
  project = %q
}
`, projectID)
	_ = os.WriteFile(filepath.Join(dir, "providers.tf"), []byte(prov), 0o644)

	run.Log.Info("Export", "wrote %d import blocks (%d unmapped) -> %s", len(items), len(unmapped), dir)

	mode := "import"
	if run.Config.HCLOnly {
		mode = "hcl-only"
	}

	// --- terraform init + generate-config-out (draft HCL; experimental) ---
	r := tf.New(dir)
	if out, err := r.Init(ctx); err != nil {
		run.Log.Warn("Export", "terraform init failed: %v", err)
		run.Log.Verbose("Export", "%s", tail(out, 20))
	} else {
		gen := filepath.Join(dir, "generated.tf")
		if out, err := r.GenerateConfig(ctx, gen); err != nil {
			run.Log.Warn("Export", "generate-config-out (experimental) had errors; born-correct import.tf still written")
			run.Log.Verbose("Export", "%s", tail(out, 30))
		} else {
			n := scrubGeneratedHCL(gen)
			run.Log.Info("Export", "generated draft HCL (%d sensitive value(s) scrubbed) -> %s", n, gen)
		}
	}

	mapped := make([]string, len(items))
	for i := range items {
		mapped[i] = items[i].res.ID
	}
	return &provider.ExportResult{
		Mode: mode,
		Containers: []provider.ContainerExport{{
			Container: projectID, Dir: dir, MappedIDs: mapped, UnmappedIDs: unmapped, Renames: len(items),
		}},
	}, nil
}

// scrubGeneratedHCL blanks out sensitive-looking string attributes that
// -generate-config-out emits in plaintext. Returns how many it scrubbed.
var sensitiveAttr = regexp.MustCompile(`^(\s*)([A-Za-z0-9_]*(secret|password|private_key|token|credential)[A-Za-z0-9_]*)(\s*)=(\s*)".*"(.*)$`)

func scrubGeneratedHCL(path string) int {
	data, err := os.ReadFile(path)
	if err != nil {
		return 0
	}
	lines := strings.Split(string(data), "\n")
	n := 0
	for i, l := range lines {
		if m := sensitiveAttr.FindStringSubmatch(l); m != nil {
			lines[i] = m[1] + m[2] + m[4] + "=" + m[5] + `"" # TerraLift: scrubbed sensitive value` + m[6]
			n++
		}
	}
	if n > 0 {
		_ = os.WriteFile(path, []byte(strings.Join(lines, "\n")), 0o644)
	}
	return n
}

// notImportable filters GCP-managed resources that exist but aren't valid user
// import targets — e.g. the default/service-agent service accounts, whose
// account_id (a project number or "service-...") the google_service_account
// schema rejects. User SAs are "<name>@<project>.iam.gserviceaccount.com".
func notImportable(r *model.Resource) bool {
	if r.TFType == "google_service_account" {
		email, _ := r.Properties["email"].(string)
		if email == "" {
			email = r.Name[strings.LastIndex(r.Name, "/")+1:]
		}
		switch {
		case strings.Contains(email, "@developer.gserviceaccount.com"),
			strings.Contains(email, "@appspot.gserviceaccount.com"),
			strings.Contains(email, "@cloudservices.gserviceaccount.com"),
			strings.Contains(email, "gcp-sa-"), strings.HasPrefix(email, "service-"):
			return true
		}
	}
	return false
}

func tail(s string, lines int) string {
	parts := strings.Split(strings.TrimRight(s, "\n"), "\n")
	if len(parts) > lines {
		parts = parts[len(parts)-lines:]
	}
	return strings.Join(parts, "\n")
}
