package gcp

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/cyberproaustin/terralift/internal/core"
	"github.com/cyberproaustin/terralift/internal/model"
	"github.com/cyberproaustin/terralift/internal/naming"
	"github.com/cyberproaustin/terralift/internal/provider"
	"github.com/cyberproaustin/terralift/internal/tf"
)

// export produces born-correct Terraform for the enumerated inventory:
//  1. classify each resource: export (user-managed, mappable) / exclude
//     (GCP-managed default, sub-resource, noise) / gap (unsupported type),
//  2. derive each exported resource's import ID from its CAI asset name,
//  3. author native `import { to = google_x.<real-name>; id = ... }` blocks — WE
//     control the address, so names are born correct (naming.Dedupe),
//  4. `terraform init` + `plan -generate-config-out` to draft the HCL,
//  5. scrub any leaked sensitive values from the generated draft.
func export(ctx context.Context, run *core.Run, inv *model.Inventory) (*provider.ExportResult, error) {
	projectID := naming.Sanitize(run.Scope.ID) // path-safe; scope id is an operator flag
	dir := filepath.Join(run.Paths.Export, projectID)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}

	// Deterministic order by canonical id so born-correct suffixes are stable.
	ids := make([]string, 0, len(inv.Resources))
	for id := range inv.Resources {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	type item struct {
		res      *model.Resource
		importID string
	}
	var items []item
	var addrs []naming.Address
	var excluded, gap []string
	for _, id := range ids {
		r := inv.Resources[id]
		if reason := excludedReason(r); reason != "" { // GCP-managed / default / sub-resource / noise
			excluded = append(excluded, r.ID)
			continue
		}
		if r.TFType == "" { // no TF mapping -> genuine coverage gap
			gap = append(gap, r.ID)
			continue
		}
		items = append(items, item{res: r, importID: deriveImportID(r.ID, r.TFType, run.Scope.ID)})
		addrs = append(addrs, naming.Address{Type: r.TFType, Base: naming.Sanitize(r.Name)})
	}
	names := naming.Dedupe(addrs) // born-correct, de-collided addresses

	// --- born-correct import blocks + address map (for reference rewire) ---
	addrByID := make(map[string]string, len(items))
	var b strings.Builder
	b.WriteString("# Generated by TerraLift — born-correct import blocks.\n")
	b.WriteString("# `terraform apply` imports these into state at the chosen addresses.\n\n")
	for i, it := range items {
		addr := it.res.TFType + "." + names[i]
		// Rewire needs to match every form a resource's id can take in generated
		// HCL: the CAI asset name, its self-link, and its fully-qualified relative
		// path (projects/...). Bare names are too generic to add safely.
		addrByID[it.res.ID] = addr
		if strings.HasPrefix(it.importID, "projects/") {
			addrByID[it.importID] = addr
		}
		if sl, ok := it.res.Properties["selfLink"].(string); ok && sl != "" {
			addrByID[sl] = addr
		}
		fmt.Fprintf(&b, "import {\n  to = %s\n  id = %q\n}\n\n", addr, it.importID)
	}
	if err := os.WriteFile(filepath.Join(dir, "import.tf"), []byte(b.String()), 0o644); err != nil {
		return nil, err
	}

	// --- providers.tf ---
	prov := fmt.Sprintf(`terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 7.0"
    }
  }
}

provider "google" {
  project = %q
}
`, run.Scope.ID)
	_ = os.WriteFile(filepath.Join(dir, "providers.tf"), []byte(prov), 0o644)

	run.Log.Info("Export", "%d resource import blocks (%d excluded, %d gap) -> %s", len(items), len(excluded), len(gap), dir)

	mode := "import"
	if run.Config.HCLOnly {
		mode = "hcl-only"
	}

	// --- terraform init + generate-config-out (draft HCL; experimental) ---
	r := tf.New(dir)
	if out, err := r.Init(ctx); err != nil {
		run.Log.Warn("Export", "terraform init failed: %v", err)
		run.Log.Verbose("Export", "%s", tail(out, 20))
	} else {
		gen := filepath.Join(dir, "generated.tf")
		out, genErr := r.GenerateConfig(ctx, gen)
		// terraform writes generated.tf even when it reports over-emit errors
		// (conflicting/invalid defaults), so prune + scrub whenever it exists.
		if _, statErr := os.Stat(gen); statErr == nil {
			pruned := pruneGeneratedHCL(gen)
			n := scrubGeneratedHCL(gen)
			note := ""
			if genErr != nil {
				note = " (raw had over-emit warnings)"
			}
			run.Log.Info("Export", "generated draft HCL%s: %d over-emitted pruned, %d scrubbed -> %s", note, pruned, n, gen)
		} else {
			run.Log.Warn("Export", "generate-config-out produced no HCL: %v", genErr)
			run.Log.Verbose("Export", "%s", tail(out, 30))
		}
	}

	// --- user IAM bindings (authored directly; written AFTER generate-config-out
	// so the IAM import blocks don't interfere with the resource config gen) ---
	iamHCL, iamImports, iamN := generateIAM(inv, addrByID)
	if iamN > 0 {
		_ = os.WriteFile(filepath.Join(dir, "iam.tf"), []byte(iamHCL), 0o644)
		if fh, err := os.OpenFile(filepath.Join(dir, "import.tf"), os.O_APPEND|os.O_WRONLY, 0o644); err == nil {
			_, _ = fh.WriteString(iamImports)
			_ = fh.Close()
		}
		run.Log.Info("Export", "%d user IAM binding(s) -> iam.tf", iamN)
	}

	mapped := make([]string, len(items))
	for i := range items {
		mapped[i] = items[i].res.ID
	}
	return &provider.ExportResult{
		Mode: mode,
		Containers: []provider.ContainerExport{{
			Container: run.Scope.ID, Dir: dir, MappedIDs: mapped,
			ExcludedIDs: excluded, GapIDs: gap, AddressByID: addrByID,
			ConfigFiles: []string{"generated.tf"}, Renames: len(items),
		}},
	}, nil
}

// excludedReason returns a non-empty reason when a resource is intentionally NOT
// an onboarding target: GCP-managed service accounts, auto-created default
// networking, sub-resources, and control-plane noise. These are separated from
// genuine "unsupported type" gaps so the coverage metric stays honest.
func excludedReason(r *model.Resource) string {
	switch r.NativeType {
	case "serviceusage.googleapis.com/Service":
		return "api-enablement (serviceusage)"
	case "cloudbilling.googleapis.com/ProjectBillingInfo":
		return "billing metadata"
	case "compute.googleapis.com/Project":
		return "compute project metadata"
	case "secretmanager.googleapis.com/SecretVersion":
		return "secret version (data-plane sub-resource)"
	case "compute.googleapis.com/Route":
		return "auto-created route"
	case "cloudresourcemanager.googleapis.com/Project":
		return "the operating project itself"
	}
	if notImportable(r) {
		return "google-managed service account"
	}
	name := lastSegment(r.ID)
	if r.NativeType == "compute.googleapis.com/Network" && name == "default" {
		return "default network"
	}
	if r.NativeType == "compute.googleapis.com/Firewall" && strings.HasPrefix(name, "default-allow-") {
		return "default firewall"
	}
	if r.NativeType == "compute.googleapis.com/Subnetwork" {
		if net, _ := r.Properties["network"].(string); strings.HasSuffix(net, "/networks/default") {
			return "default-network subnetwork"
		}
	}
	return ""
}

// notImportable filters GCP-managed service accounts (default / service-agent),
// whose account_id the google_service_account schema rejects.
func notImportable(r *model.Resource) bool {
	if r.TFType != "google_service_account" {
		return false
	}
	email, _ := r.Properties["email"].(string)
	if email == "" {
		email = lastSegment(r.ID)
	}
	switch {
	case strings.Contains(email, "@developer.gserviceaccount.com"),
		strings.Contains(email, "@appspot.gserviceaccount.com"),
		strings.Contains(email, "@cloudservices.gserviceaccount.com"),
		strings.Contains(email, "gcp-sa-"), strings.HasPrefix(email, "service-"):
		return true
	}
	return false
}

// scrubGeneratedHCL blanks out sensitive VALUE attributes that
// -generate-config-out can emit in plaintext. Matched by EXACT attribute name
// (a payload field), NOT any name merely containing a keyword — matching by
// substring wrongly blanks control-plane fields like secret_id / kms_key_name.
var sensitiveAttr = regexp.MustCompile(`(?i)^(\s*)(secret_data|password|passphrase|private_key|private_key_pem|client_secret|client_key|access_token|auth_token|sas_token|connection_string|service_account_key|credentials|private_key_id)(\s*)=(\s*)(".*"|<<.*)(.*)$`)

func scrubGeneratedHCL(path string) int {
	data, err := os.ReadFile(path)
	if err != nil {
		return 0
	}
	lines := strings.Split(string(data), "\n")
	n := 0
	for i, l := range lines {
		if m := sensitiveAttr.FindStringSubmatch(l); m != nil {
			lines[i] = m[1] + m[2] + m[3] + "=" + m[4] + `"" # TerraLift: scrubbed sensitive value`
			n++
		}
	}
	if n > 0 {
		_ = os.WriteFile(path, []byte(strings.Join(lines, "\n")), 0o644)
	}
	return n
}

// pruneGeneratedHCL removes attributes that -generate-config-out over-emits with
// unset/default values (null, [], {}, 0). These add nothing, and emitting BOTH
// sides of a mutually-exclusive pair as empty lists (e.g. source_tags = [] and
// source_service_accounts = []) makes terraform reject the config. Removing them
// lets the provider apply its real defaults — the resource is reproduced faithfully.
var emptyAttr = regexp.MustCompile(`^\s*[A-Za-z0-9_]+\s*=\s*(null|\[\]|\{\}|0)\s*$`)

// overEmitAttr matches google-provider attributes that -generate-config-out emits
// with default values that are INVALID in the resource's actual mode (e.g.
// bgp_always_compare_med is rejected under the default LEGACY best-path mode).
// Dropping them lets the provider apply the correct default.
var overEmitAttr = regexp.MustCompile(`^\s*(bgp_always_compare_med|delete_bgp_always_compare_med)\s*=`)

func pruneGeneratedHCL(path string) int {
	data, err := os.ReadFile(path)
	if err != nil {
		return 0
	}
	lines := strings.Split(string(data), "\n")
	out := make([]string, 0, len(lines))
	n := 0
	for _, l := range lines {
		if emptyAttr.MatchString(l) || overEmitAttr.MatchString(l) {
			n++
			continue
		}
		out = append(out, l)
	}
	if n > 0 {
		_ = os.WriteFile(path, []byte(strings.Join(out, "\n")), 0o644)
	}
	return n
}

func tail(s string, lines int) string {
	parts := strings.Split(strings.TrimRight(s, "\n"), "\n")
	if len(parts) > lines {
		parts = parts[len(parts)-lines:]
	}
	return strings.Join(parts, "\n")
}
