package gcp

import (
	"fmt"
	"strings"

	"github.com/cyberproaustin/terralift/internal/model"
	"github.com/cyberproaustin/terralift/internal/naming"
)

// generateIAM authors google_*_iam_member HCL + born-correct import blocks for
// USER-created IAM bindings (users, groups, user service accounts, allUsers).
// Google-managed service agents are skipped (auto-granted, not user IaC). IAM
// members are simple 3-field resources, so we author them directly rather than
// relying on the experimental generate-config-out. Returns (hcl, importBlocks, n).
func generateIAM(inv *model.Inventory, addrByID map[string]string) (string, string, int) {
	type binding struct {
		tfType, ownerAttr, ownerExpr, role, member, importID string
	}
	var bs []binding
	seen := map[string]bool{}
	for _, b := range inv.IAM {
		if !isUserMember(b.PrincipalID) {
			continue
		}
		// Skip default bucket ACL roles — GCP auto-creates them on every bucket;
		// they are not user IaC and would clutter the export.
		if strings.HasPrefix(b.Role, "roles/storage.legacy") {
			continue
		}
		tfType, attr, ownerVal, importOwner := iamResourceFor(b.Scope)
		if tfType == "" {
			continue // unsupported scope -> skip (not a hard gap; IAM types grow incrementally)
		}
		key := b.Scope + "|" + b.Role + "|" + b.PrincipalID
		if seen[key] {
			continue
		}
		seen[key] = true
		// Reference the managed owner resource (dependency ordering) when we
		// exported it; otherwise a quoted literal (e.g. the project itself).
		ownerExpr := fmt.Sprintf("%q", ownerVal)
		if addr, ok := addrByID[b.Scope]; ok {
			switch tfType {
			case "google_storage_bucket_iam_member":
				ownerExpr = addr + ".name"
			case "google_service_account_iam_member":
				ownerExpr = addr + ".email"
			case "google_pubsub_topic_iam_member":
				ownerExpr = addr + ".id"
			}
		}
		bs = append(bs, binding{
			tfType: tfType, ownerAttr: attr, ownerExpr: ownerExpr, role: b.Role, member: b.PrincipalID,
			importID: importOwner + " " + b.Role + " " + b.PrincipalID,
		})
	}
	if len(bs) == 0 {
		return "", "", 0
	}

	addrs := make([]naming.Address, len(bs))
	for i, b := range bs {
		addrs[i] = naming.Address{Type: b.tfType, Base: naming.Sanitize(shortRole(b.role) + "_" + shortMember(b.member))}
	}
	names := naming.Dedupe(addrs)

	var hcl, imp strings.Builder
	hcl.WriteString("# Generated by TerraLift — user IAM bindings.\n\n")
	for i, b := range bs {
		fmt.Fprintf(&hcl, "resource %q %q {\n  %s = %s\n  role   = %q\n  member = %q\n}\n\n",
			b.tfType, names[i], b.ownerAttr, b.ownerExpr, b.role, b.member)
		fmt.Fprintf(&imp, "import {\n  to = %s.%s\n  id = %q\n}\n\n", b.tfType, names[i], b.importID)
	}
	return hcl.String(), imp.String(), len(bs)
}

// iamResourceFor maps a binding's CAI scope to the IAM-member resource type, the
// HCL owner attribute + value, and the import-id owner token.
func iamResourceFor(scope string) (tfType, ownerAttr, ownerVal, importOwner string) {
	switch {
	case strings.Contains(scope, "//cloudresourcemanager.googleapis.com/projects/"):
		p := lastSegment(scope)
		return "google_project_iam_member", "project", p, p
	case strings.Contains(scope, "//storage.googleapis.com/"):
		b := lastSegment(scope)
		return "google_storage_bucket_iam_member", "bucket", b, "b/" + b
	case strings.Contains(scope, "//iam.googleapis.com/") && strings.Contains(scope, "/serviceAccounts/"):
		id := stripService(scope)
		return "google_service_account_iam_member", "service_account_id", id, id
	case strings.Contains(scope, "//pubsub.googleapis.com/") && strings.Contains(scope, "/topics/"):
		t := stripService(scope)
		return "google_pubsub_topic_iam_member", "topic", t, t
	}
	return "", "", "", ""
}

// isUserMember reports whether an IAM member is user-created (not a Google
// service agent, which GCP auto-grants and terraform should not manage).
func isUserMember(member string) bool {
	switch {
	case strings.Contains(member, "@developer.gserviceaccount.com"),
		strings.Contains(member, "@appspot.gserviceaccount.com"),
		strings.Contains(member, "@cloudservices.gserviceaccount.com"),
		strings.Contains(member, "gcp-sa-"),
		strings.HasPrefix(member, "serviceAccount:service-"),
		// projectOwner/Editor/Viewer: GCP's default bucket-ACL convenience
		// members, auto-created — not user-authored bindings.
		strings.HasPrefix(member, "projectOwner:"),
		strings.HasPrefix(member, "projectEditor:"),
		strings.HasPrefix(member, "projectViewer:"):
		return false
	}
	return true
}

func shortRole(role string) string { return lastSegment(role) } // roles/storage.objectViewer -> storage.objectViewer
func shortMember(member string) string {
	m := member
	if i := strings.Index(m, ":"); i >= 0 {
		m = m[i+1:] // drop "user:"/"serviceAccount:" prefix
	}
	if i := strings.Index(m, "@"); i >= 0 {
		m = m[:i] // drop domain
	}
	return m
}
