package mackerel

import (
	"context"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/cyberproaustin/terralift/internal/core"
	"github.com/cyberproaustin/terralift/internal/hcl"
	"github.com/cyberproaustin/terralift/internal/model"
	"github.com/cyberproaustin/terralift/internal/naming"
	"github.com/cyberproaustin/terralift/internal/provider"
	"github.com/cyberproaustin/terralift/internal/tf"
)

// export produces born-correct import blocks + a providers.tf, drafts config via
// `terraform plan -generate-config-out`, and keeps only the import blocks whose config
// generated (the rest are honest gaps). One flat container: the org.
func export(ctx context.Context, run *core.Run, inv *model.Inventory) (*provider.ExportResult, error) {
	org := run.Scope.ID
	dir := filepath.Join(run.Paths.Export, naming.Sanitize(org))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}

	ids := make([]string, 0, len(inv.Resources))
	for id := range inv.Resources {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	type item struct {
		res      *model.Resource
		importID string
	}
	var items []item
	var addrs []naming.Address
	var excluded, gap []string
	for _, id := range ids {
		r := inv.Resources[id]
		if reason := excludedReason(r); reason != "" {
			excluded = append(excluded, r.ID)
			continue
		}
		if r.TFType == "" {
			gap = append(gap, r.ID)
			continue
		}
		items = append(items, item{res: r, importID: deriveImportID(r)})
		addrs = append(addrs, naming.Address{Type: r.TFType, Base: naming.Sanitize(r.Name)})
	}
	names := naming.Dedupe(addrs)

	itemAddr := make([]string, len(items))
	var b strings.Builder
	b.WriteString("# Generated by TerraLift — born-correct import blocks.\n")
	b.WriteString("# `terraform apply` imports these into state at the chosen addresses.\n\n")
	for i, it := range items {
		itemAddr[i] = it.res.TFType + "." + names[i]
		b.WriteString(hcl.ImportBlock(itemAddr[i], it.importID))
	}
	if err := os.WriteFile(filepath.Join(dir, "import.tf"), []byte(b.String()), 0o644); err != nil {
		return nil, err
	}

	prov := `terraform {
  required_providers {
    mackerel = {
      source  = "mackerelio-labs/mackerel"
      version = "~> 0.9"
    }
  }
}

provider "mackerel" {
  # Auth via the MACKEREL_APIKEY environment variable (never inline the api key in config —
  # Terraformer inlines it, which is a leak). Set MACKEREL_API_BASE for an enterprise/KCPS host.
}
`
	if err := os.WriteFile(filepath.Join(dir, "providers.tf"), []byte(prov), 0o644); err != nil {
		return nil, err
	}

	run.Log.Info("Export", "%d resource import blocks (%d excluded, %d gap) -> %s", len(items), len(excluded), len(gap), dir)

	mode := "import"
	if run.Config.HCLOnly {
		mode = "hcl-only"
	}

	var redactions []hcl.Redaction
	r := tf.New(dir)
	if out, err := r.Init(ctx); err != nil {
		run.Log.Warn("Export", "terraform init failed: %v", err)
		run.Log.Verbose("Export", "%s", hcl.Tail(out, 20))
	} else {
		gen := filepath.Join(dir, "generated.tf")
		_, genErr := r.GenerateConfig(ctx, gen)
		if _, statErr := os.Stat(gen); statErr == nil {
			pruned := pruneGeneratedHCL(gen)
			redactions = scrubGeneratedHCL(gen)
			note := ""
			if genErr != nil {
				note = " (raw had over-emit warnings)"
			}
			run.Log.Info("Export", "generated draft HCL%s: %d pruned, %d scrubbed -> %s", note, pruned, len(redactions), gen)
		} else {
			run.Log.Warn("Export", "generate-config-out produced no HCL: %v", genErr)
		}
	}

	generated := hcl.ScanAddrsFile(filepath.Join(dir, "generated.tf"))
	cands := make([]hcl.ImportCandidate, len(items))
	for i, it := range items {
		cands[i] = hcl.ImportCandidate{Addr: itemAddr[i], ImportID: it.importID}
	}
	mappedIdx, gapIdx, _ := hcl.SplitByGenerated(filepath.Join(dir, "import.tf"), hcl.ImportHeader, generated, cands)

	mapped := make([]string, 0, len(mappedIdx))
	refByID := make(map[string]string, len(mappedIdx))
	for _, i := range mappedIdx {
		it := items[i]
		mapped = append(mapped, it.res.ID)
		refByID[it.res.ID] = itemAddr[i] + ".id"
	}
	for _, i := range gapIdx {
		gap = append(gap, items[i].res.ID)
	}
	if len(gapIdx) > 0 {
		run.Log.Info("Export", "dropped %d import block(s) with no generated config", len(gapIdx))
	}

	return &provider.ExportResult{
		Mode: mode,
		Containers: []provider.ContainerExport{{
			Container: org, Dir: dir, MappedIDs: mapped,
			ExcludedIDs: excluded, GapIDs: gap, AddressByID: refByID,
			ConfigFiles: []string{"generated.tf"}, Redactions: redactions,
		}},
	}, nil
}

// excludedReason returns a non-empty reason when a resource is enumerated but must NOT be adopted.
// Mackerel's secrets are FIELD-LEVEL write-only (channel url/token, aws_integration secret_key,
// monitor external headers) — Phase-B scrubs on adoptable shells, never decoded here — so there is
// no whole write-only resource to exclude. This seam stays for Phase B.
func excludedReason(r *model.Resource) string {
	return ""
}
