package azure

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/cyberproaustin/terralift/internal/model"
	"github.com/cyberproaustin/terralift/internal/naming"
	"github.com/cyberproaustin/terralift/internal/util"
)

// generateRoleAssignments authors azurerm_role_assignment HCL + born-correct
// import blocks for the RBAC bindings scoped WITHIN a resource group (RG-level
// and resource-level; subscription-level bindings are omitted — they aren't
// specific to this group and would duplicate across stacks). The import blocks
// adopt the existing assignments so `terraform apply` never recreates them. When
// the scoped resource is exported in this stack, scope references it by address
// (dependency ordering + migration retargeting); otherwise a literal id.
// Returns the HCL and the number of assignments authored.
func generateRoleAssignments(inv *model.Inventory, container string, addrByID map[string]string) (string, int) {
	want := strings.ToLower(container)
	// Case-insensitive scope -> managed-resource address (cloud IDs are
	// case-insensitive and the enumerate/export sources differ in casing).
	addrLower := make(map[string]string, len(addrByID))
	for id, addr := range addrByID {
		addrLower[strings.ToLower(id)] = addr
	}

	picked := make([]model.IAMBinding, 0)
	seen := map[string]bool{}
	for _, b := range inv.IAM {
		if b.ID == "" { // no native id -> can't author an import block
			continue
		}
		m := scopeRGRe.FindStringSubmatch(b.Scope)
		if m == nil || strings.ToLower(m[1]) != want { // not scoped inside this RG
			continue
		}
		if seen[b.ID] {
			continue
		}
		seen[b.ID] = true
		picked = append(picked, b)
	}
	if len(picked) == 0 {
		return "", 0
	}
	// Deterministic order by binding id so born-correct suffixes are stable.
	sort.Slice(picked, func(i, j int) bool { return picked[i].ID < picked[j].ID })

	addrs := make([]naming.Address, len(picked))
	for i, b := range picked {
		addrs[i] = naming.Address{Type: "azurerm_role_assignment", Base: roleAssignmentName(b)}
	}
	names := naming.Dedupe(addrs)

	var sb strings.Builder
	sb.WriteString("# Generated by TerraLift — Azure RBAC captured as code (control-plane).\n")
	sb.WriteString("# import blocks adopt the existing assignments; apply will not recreate them.\n\n")
	for i, b := range picked {
		label := names[i]
		// scope: reference the managed resource when we exported it; else a literal
		// id (HCL-template-escaped). The import id stays literal ALWAYS.
		scopeExpr := fmt.Sprintf("%q", util.EscapeHCLTemplate(b.Scope))
		if addr, ok := addrLower[strings.ToLower(b.Scope)]; ok {
			scopeExpr = addr + ".id"
		}
		// Prefer role_definition_name (readable, portable across tenants), but a name
		// that is still a raw GUID never resolved (e.g. az role-definition read was
		// denied / a custom role) — role_definition_name can't accept a GUID, so fall
		// back to the canonical role_definition_id, which azurerm resolves directly.
		roleField := fmt.Sprintf("role_definition_name = %q", util.EscapeHCLTemplate(b.Role))
		if isRoleGUID(b.Role) && b.RoleID != "" {
			roleField = fmt.Sprintf("role_definition_id   = %q", util.EscapeHCLTemplate(b.RoleID))
		}
		fmt.Fprintf(&sb, "import {\n  to = azurerm_role_assignment.%s\n  id = %q\n}\n\n", label, util.EscapeHCLTemplate(b.ID))
		fmt.Fprintf(&sb, "resource \"azurerm_role_assignment\" %q {\n  scope                = %s\n  %s\n  principal_id         = %q\n}\n\n",
			label, scopeExpr, roleField, util.EscapeHCLTemplate(b.PrincipalID))
	}
	return sb.String(), len(picked)
}

// roleGUIDRe matches a bare role-definition GUID (resolveRole's fallback when it
// can't map the id to a friendly name).
var roleGUIDRe = regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`)

func isRoleGUID(s string) bool { return roleGUIDRe.MatchString(s) }

// roleAssignmentName builds a born-correct label from the role name plus a short
// slice of the assignment's OWN guid. Using the assignment guid (the resource's
// stable identity) — not the principal — keeps addresses stable across runs even
// when a principal holds the same role at multiple scopes in one group.
func roleAssignmentName(b model.IAMBinding) string {
	guid := b.ID
	if i := strings.LastIndex(guid, "/"); i >= 0 {
		guid = guid[i+1:]
	}
	short := strings.ReplaceAll(guid, "-", "")
	if len(short) > 8 {
		short = short[:8]
	}
	base := b.Role
	if short != "" {
		base = b.Role + "_" + short
	}
	return naming.Sanitize(base)
}
